data/org.freedesktop.impl.portal.Print.xml, data/org.freedesktop.portal.Print.xml, src/Makefile.am.inc, src/print.c, src/print.h, src/xdg-desktop-portal.c
For now, this just has a PrintFile method.
=> Implement a simple print portal

data/org.freedesktop.portal.FileChooser.xml, data/org.freedesktop.portal.OpenURI.xml, data/org.freedesktop.portal.Print.xml, data/org.freedesktop.portal.Request.xml, src/file-chooser.c, src/open-uri.c, src/print.c
Most of the portals use the same kind of response, so we should be able to reuse one.
=> Add a standard response for org.freedesktop.portal.Request

src/request.c
When we switched to the common request object, we lost the important
detail that Response signals are only sent to the application that
made the request. Bring that back.
=> Don't broadcast response signals

data/org.freedesktop.portal.FileChooser.xml, src/file-chooser.c
We pass through options both ways. Also update the documentation.
=> Implement combobox support for the file chooser

src/open-uri.c
Otherwise, simply skip the call to the backend and launch the only candidate
application rightaway, to make the process smoother.
Note that this only applies for http:// and https:// URI schemes. Any other
scheme will show the chooser dialog even if only one candidate exists.
Fixes issue https://github.com/flatpak/xdg-desktop-portal/issues/30
=> open-uri: Only show the chooser dialog for http[s] when having several options

doc/portal-docs.xml
No need for a mixture of xinclude and entity inclusions.
=> Use xinclude for the version fragment

src/open-uri.c
Another instance of key <> format_string confusion in g_variant_lookup.
=> Make open-uri work

data/org.freedesktop.impl.portal.AppChooser.xml, data/org.freedesktop.impl.portal.FileChooser.xml, data/org.freedesktop.impl.portal.Inhibit.xml, data/org.freedesktop.impl.portal.Notification.xml, data/org.freedesktop.impl.portal.Print.xml, data/org.freedesktop.impl.portal.Screenshot.xml
This is required in order to be able to generate source code using qdbusxml2cpp.
=> Add Qt annotations into xml files

src/documents.c, src/open-uri.c, src/xdg-desktop-portal.c
=> Misc fixes

src/open-uri.c
Add a third field to the data stored to store the threshold used to know
when not to show the dialog for http(s) schemes, so that it can be set
to something different from the hardcoded default value, per application.
https://github.com/flatpak/xdg-desktop-portal/issues/32
=> open-uri: Allow configuring threshold to skip the dialog per application

src/open-uri.c
Due to a mistake introduced in commit b8f34737, the data from the permissions
store is not correctly handled the first time a flatpak requires opening an
URI, resulting in setting the threshold for that app always to zero, which
prevents the dialog from ever showing again.
To fix this, set defaults for the values returned by get_latest_choice_info(),
so that it always returns the less restrictive values by default (i.e. no
threshold, always ask) unless a different one has been explicitly set.
https://github.com/flatpak/xdg-desktop-portal/issues/32
=> open-uri: Set sane defaults when reading info from the permissions store

po/sr.po
Serbian translation from Gnome Damned Lies.
=> Serbian translation

src/open-uri.c
* Fix a free of invalid memory when bogus file:///URLs are passed
* Remove leftover prints for debugging
=> Miscellaneous fixes

data/Makefile.am.inc, data/org.freedesktop.impl.portal.Email.xml, data/org.freedesktop.portal.Email.xml, doc/Makefile.am, doc/portal-docs.xml.in, src/Makefile.am.inc, src/email.c, src/email.h, src/xdg-desktop-portal.c
This portal adds a simple method to send an email.
=> Add an email portal

src/notification.c
=> notification: Subscribe to the right interface for signals

data/org.freedesktop.impl.portal.AppChooser.xml, src/open-uri.c
The latest mockups of the app chooser call for displaying
the uri as well, so pass it along.
=> Send more data to the app chooser

src/screenshot.c
Spotted by Coverity, CID 207679.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
=> screenshot: Gracefully handle an option not being provided

src/documents.c
Make use of new AddFull() method where we can specify with flags whether
the document portal should return real path to file we have access to or
whether it should return path to fuse mountpoint
=> Return real path when opening files we have access to

data/org.freedesktop.portal.Documents.xml
@flags is a bitfield, so the 3rd value is 4, not 3.
=> documents xml: Correct flag value for as-needed-by-app

po/LINGUAS, po/zh_TW.po
I have just done Chinese (Taiwan) translation.
Thanks!
=> Add Chinese (Taiwan) translation

RELEASE_HOWTO.md
This is how I've done releases so far.
=> Add some quick checklist for releases

src/documents.c
Clarify what flags we pass to the document portal.
=> Add a few comments

document-portal/document-portal-fuse.c, tests/test-doc-portal.c
This fixes:
https://github.com/flatpak/xdg-desktop-portal/issues/230
But also some other stuff that I found when adding the tests to find the issues.
Additionally it adds some docs on the ownership of XdpInodes.
=> document portal tests and various fixes to make them complete

tests/Makefile.am.inc, tests/test-permission-store.c
For now, this tests that change notification works.
=> Add some permission store tests

glib-tap.mk, src/remote-desktop.c, src/screen-cast.c, tests/test-permission-store.c
This includes:
* Makes test pass (failed due to uninitialized variable)
* Silences Makefile warning
* Silences compiler warning with newer glib
=> Some minor fixes

document-portal/document-portal.c
We don't generally daemonize in session services.
Tests run the service in the foreground, and in
regular use, it gets activated on the bus, which
already does all thats necessary.
Closes: #244
=> document portal: Remove --daemon option

data/Makefile.am.inc, data/org.freedesktop.impl.portal.Settings.xml, src/Makefile.am.inc, src/settings.c, src/settings.h, src/xdg-desktop-portal.c
I have not tested this with an actual backend but this should be the general idea.
Do not merge until tested.
CC @grulja
=> WIP: settings: Support backend implementation

src/inhibit.c
The permissions are expected to be empty - we allow all
inhibiting by default. We should not warn in this case,
reduce this to debug spew, and add some more in other
places.
Closes: #272
=> inhibit: Don't warn for harmless things

src/xdg-desktop-portal.c
Print option parsing errors more nicely,
and add a --version option.
=> Improve commandline handling

src/Makefile.am.inc, src/account.c, src/email.c, src/file-chooser.c, src/print.c, src/remote-desktop.c, src/screen-cast.c, src/screenshot.c, src/xdp-utils.c, src/xdp-utils.h
We should validate email addresses
=> Email validation

src/email.c, src/inhibit.c
Remove leftover debug spew and validate some more options
=> small fixes

src/notification.c
This is more convenient than setting up a sandbox ourselves, and guarantees that the tool gets a working, tight sandbox.
This depends on https://github.com/flatpak/flatpak/pull/2618
=> notification: Use builtin sandboxing for icon validator

document-portal/document-portal-fuse.c
We're in the process of backporting xdg-desktop-portal 1.0.3 to older Ubuntu releases, and ran into document portal test failures on Ubuntu 18.04.  Here's one example of the test run:
```
Running test: xdg-desktop-portal/test-doc-portal.test
outdir: /tmp/xdp-test-O0ZGYZ
dbus-daemon[1003]: [session uid=1000 pid=1003] Activating service name='org.freedesktop.portal.Documents' requested by ':1.0' (uid=1000 pid=1001 comm="/usr/libexec/installed-tests/xdg-desktop-portal/te" label="unconfined")
dbus-daemon[1003]: [session uid=1000 pid=1003] Activating service name='org.freedesktop.impl.portal.PermissionStore' requested by ':1.1' (uid=1000 pid=1008 comm="/usr/libexec/xdg-document-portal " label="unconfined")
dbus-daemon[1003]: [session uid=1000 pid=1003] Successfully activated service …
```
=> document-portal: make xdp_inode_kernel_unref check that kernel_ref_count > 0

src/Makefile.am.inc, src/portal-impl.c, src/portal-impl.h, src/xdg-desktop-portal.c
This will make it easier to share this code
with the flatpak portal, which also wants
to find and use some portal backends.
=> Break out the portal finding code

src/xdp-utils.c
Newer versions of bubblewrap write the namespace information to the
bwrapinfo.json. Try reading that information and thus avoiding the
extra work to look up the pid namespace information via /proc.
Fallback to this old mechanism if the bwrapinfo.json does not contain
the information.
This needs projectatomic/bubblewrap#323
=> utils: use namespace info from bwrap, if available

po/it.po
Signed-off-by: Milo Casagrande <milo@milo.name>
=> l10n: Update Italian translation

doc/Makefile.am, doc/portal-docs.xml.in
=> Distribute Wallpaper Portal docs

.github/workflows/check.yml
=> Use github actions for CI

tests/inhibit.c, tests/test-portals.c
=> Actually add the location accuracy test

data/org.freedesktop.impl.portal.PermissionStore.xml, document-portal/permission-db.c, document-portal/permission-db.h, document-portal/xdg-permission-store.c, tests/test-permission-store.c
Add a DeletePermission method to the permission store.
=> Permission delete app

data/org.freedesktop.portal.OpenURI.xml, src/open-uri.c, tests/openuri.c, tests/openuri.h, tests/test-portals.c
Set the default threshold for how often to ask the user to choose the same handler to 3.
This limits the annoyance.
=> Openuri threshold

tests/backend/email.c, tests/email.c
The libportal api for email has changed.
Update to match.
=> Update email tests

src/wallpaper.c, src/wallpaper.h, src/xdg-desktop-portal.c
This was only working by accident.
=> wallpaper: Use the right access backend

.github/workflows/check.yml, data/org.freedesktop.impl.portal.Background.xml, src/background.c, tests/inhibit.c
Redo the background monitoring to reduce the delay between an application closing its last window and the notification.
=> Background: better monitoring

tests/openuri.c
See https://github.com/flatpak/libportal/commit/86d65142a9625dede91f88fbf21febc37916a2e8
=> tests: Update for libportal API change

data/org.freedesktop.portal.Print.xml
Clarify that page ranges are 0-based.
=> Print docs

tests/Makefile.am.inc, tests/backend/Makefile.am.inc, tests/backend/email.c, tests/filechooser.c, tests/glib-backports.c, tests/glib-backports.h
Add backports for new api that we're using in tests.
=> Fix the build on old glib

.github/workflows/check.yml, src/permissions.c, src/xdp-utils.c
This doesn't build libportal because that needs a new meson.
=> Add CI tests for xenial

configure.ac, src/camera.c, src/pipewire.c, src/pipewire.h, src/screen-cast.c
This MR upates the API to the upcoming 3.0 API of PipeWire
=> PipeWire: update to 0.3 API

configure.ac
Reverts flatpak/xdg-desktop-portal#451
=> Revert "configure.ac: Report early when flatpak is not installed"

README.md
Hi,
Just tried the wlroots backend, works well (still in development). 
Cheers, thanks for the work.
=> Add wlroots backend

document-portal/document-portal-fuse.c, tests/test-document-fuse.py
A path like /some/path/with/subdir now gets exposed as a document
directory '/run/user/1000/doc/1234abcd' with a 'subdir' child.
This means the actual name of the directory will be visible to
the app (and user) rather than some weird generated id.
Fixes https://github.com/flatpak/xdg-desktop-portal/issues/460
=> document-portal: Expose directory documents as a subdirectory

portal-docs.html
Might be nice to gh actions this one day but hey ho!
=> Update docs for 1.7.1 release

document-portal/document-portal-fuse.c
Define O_FSYNC if it isn't already.
Closes: #464
=> document-portal: Fix compilation with musl

doc/Makefile.am, doc/portal-docs.xml.in
I realized that I didn't add those interfaces to the documentation.
=> doc: Include secret portal documentation

data/org.freedesktop.impl.portal.ScreenCast.xml, data/org.freedesktop.portal.ScreenCast.xml
=> [ScreenCast] Fix typo and minor clarifications

src/open-uri.c
This will result in the file entry being highlighted upon opening the directory. Fixes #564.
(Also includes an fd double-close fix I found while writing this.)
=> openuri: Use FileManager1 in OpenDirectory

.github/workflows/check.yml, .github/workflows/docs.yml, doc/redirect.html
=> CI: build & deploy the docs

doc/docbook.css
This does a basic dark styling via css to make the docs a bit easier on the eyes
=> Add dark mode for docs

SECURITY.md, configure.ac
@smcv suggested doing this due to the significant changes on or soon to be on the master branch
=> Bump version and update SECURITY.md

src/background.c, src/email.c, src/file-chooser.c, src/inhibit.c, src/notification.c, src/open-uri.c, src/print.c, src/remote-desktop.c, src/screen-cast.c, src/screenshot.c, src/secret.c, src/wallpaper.c
This should make error messages less ugly.
=> Use g_dbus_error_strip_remote_error() more

src/account.c, src/background.c, src/camera.c, src/device.c, src/email.c, src/file-chooser.c, src/gamemode.c, src/inhibit.c, src/location.c, src/network-monitor.c, src/notification.c, src/open-uri.c, src/print.c, src/proxy-resolver.c, src/realtime.c, src/remote-desktop.c, src/request.c, src/screen-cast.c, src/screenshot.c, src/secret.c, src/settings.c, src/trash.c, src/wallpaper.c
This helps with readability I think.
=> Use G_DBUS_METHOD_INVOCATION_HANDLED more

document-portal/document-enums.h, document-portal/document-portal-fuse.c, document-portal/document-portal.c, document-portal/document-store.c, document-portal/document-store.h, document-portal/xdg-permission-store.h, src/account.c, src/documents.c, src/documents.h, src/file-chooser.c, src/location.c, src/open-uri.c, src/screenshot.c, src/wallpaper.c, src/xdp-utils.c
As discussed in #581, this is the work needed to make this changes possible.
=> Preparatory PR for setting unsandboxed process app IDs

data/org.freedesktop.impl.portal.ScreenCast.xml
Now it can run through qdbusxml2cpp
=> screencast: Fix type anotations for Qt

src/Makefile.am.inc, src/xdp-utils.c, src/xdp-utils.h, tests/test-xdp-utils.c
=> Fix build without systemd

src/xdp-utils.c
=> realtime: Fix crash with WebKit processes

po/LINGUAS, po/oc.po
Hello,
I hope I made all required changes.
Regards
=> lang: add OC

src/xdp-utils.c, tests/test-xdp-utils.c
Fixes https://github.com/flatpak/xdg-desktop-portal/issues/745
=> Fix a bug in cgroup parsing

tests/Makefile.am.inc, tests/backend/Makefile.am.inc
Just something that's been annoying me for a while now....
=> tests: fix some tab vs spaces issues in the Makefiles

src/screen-cast.c
The replace_restore_token_with_data() function is called both for
remote desktop and screencast sessions. However, it was always
casting and using to ScreenCastSession, even when a remote desktop
session was passed. This could lead to memory corruption.
Be more careful when casting the Session object to ScreenCastSession.
Move the casting entirely to inside replace_restore_token_with_data(),
and make sure the only code paths that perform type casting are safely
guarded by either is_remote_desktop_session or is_screen_cast_session
checks.
This is a regression from the screencast restore PR.
Closes https://github.com/flatpak/xdg-desktop-portal/issues/771
=> screencast: Don't cast remote desktop sessions to screencast

document-portal/document-portal-fuse.c, document-portal/document-portal.c, tests/account.c, tests/test-portals.c
Compiler warning fix, one type safety fix and a comment move, factored out from #717
=> Some simple cleanups

document-portal/xdg-permission-store.c, src/inhibit.c, tests/inhibit.c, tests/test-doc-portal.c, tests/test-permission-store.c, tests/test-portals.c
Mostly to improve debugging of failing test cases a bit
=> More cleanups

src/xdg-desktop-portal.service.in
=> Stop xdg-desktop-portal when the session ends

src/realtime.c, src/xdp-utils.c, src/xdp-utils.h
This is the backport for the 1.14 branch
=> Issue #837 - Remap thread ids - backport to 1.14

doc/xmlto-config.xsl
=> doc: Add viewport meta tag

doc/docbook.css
This makes the docs page fully responsive.
=> doc: Make docs fully responsive

src/global-shortcuts.c
Where we are taking arguments as variant, make sure it has the correct types inside.
=> global-shortcuts: Try harder to sanitize input options

document-portal/document-store.c, src/clipboard.c, src/dynamic-launcher.c, src/location.c, src/xdp-utils.c, tests/can-use-fuse.c, tests/print.c
=> Cleanup some unused variables

tests/meson.build
=> tests: split the pytest test suites up per file

doc/docbook.css, doc/portal-docs.xml.in
Nothing fancy. I won't continue with this as we're eventually moving towards Sphynx, but there's no reason to not make things look less bad until then.
=> Improve visuals of documentation

doc/docbook.css
=> Enhance visual experience for smaller screens

.github/workflows/check.yml
Every release we have to cross our fingers that meson dist isn't broken, and that's not fantastic. Let's test it on every pull request, so we can catch PRs that break dist earlier.
=> ci: Exercise creating dist tarball

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/bug-report.yml, RELEASE_HOWTO.md
Fancy GitHub feature that should make the issue reports a bit more actionable.
=> Add bug report form

README.md, doc/website/index.md
=> README: Elementary → elementary OS

doc/website/_config.yml
The new link is more accurate, I was inspired by the fact that I couldn't find the page at first,
=> Updated website sources URL

document-portal/document-portal-fuse.c, tests/account.c
=> Code style formatting

document-portal/document-portal-fuse.c
=> Various cleanups and a fix for the Document portal's FUSE implementation

tests/test-document-fuse.py
This should land before #1196 or require changes.
Probably more testing of the output should be done.
=> Add FileTransfer portal test

tests/test-document-fuse.py
- We need to start a new file transfer
- This was hiding legitimate failures
=> test-document-fuse: Fix test with invalid keys

data/org.freedesktop.portal.GlobalShortcuts.xml
=> typo: remove extra ``

data/org.freedesktop.impl.portal.GlobalShortcuts.xml, data/org.freedesktop.portal.GlobalShortcuts.xml
remove code from xml `</term>` and adding missing characters
=> doc: Fix rST formatting

.github/workflows/pages.yml, CONTRIBUTING.md, README.md, doc/conf.py
=> Use the Furo theme for docs

doc/conf.py, doc/implementation-interfaces.rst, doc/index.rst, doc/portal-interfaces.rst
=> Small documentation updates

doc/conf.py, doc/index.rst
=> More trivial doc fixes

meson.build, tests/meson.build
I tried to build the documentation and I was missing several dependencies.
=> docs: properly detect dependencies for documentation

.github/workflows/check.yml, tests/backend/screenshot.c, tests/filechooser.c, tests/limited-portals.c
leak detection is enabled in CI.
=> tests: Fix memory leaks

src/restore-token.c
Replace the combination of set_permission_sync() + the manual call to SetValue() with a single call to Set().
This removes the unnecessary extra D-Bus call, and makes the world an tiny little bit of a better place.
=> restore-token: Store data with a single D-Bus call

src/validate-icon.c
Even though the program is run and quit.
=> validate-icon: fix memory leaks

data/org.freedesktop.portal.GlobalShortcuts.xml
Depends on https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/82 getting merged.
=> globalshortcuts: Add a link to the xdg shortcuts spec

src/notification.c, tests/test-doc-portal.c
=> Minor cleanups

src/background.c, src/xdp-app-info-private.h, src/xdp-app-info.c, src/xdp-app-info.h, src/xdp-utils.h, tests/test-xdp-utils.c
First 3 commits of https://github.com/flatpak/xdg-desktop-portal/pull/1369
=> XdpAppInfo refactoring, intermission

CONTRIBUTING.md, doc/website/index.md
* Add COSMIC's XDG Desktop Portal to the docs
* Fix broken link for contributions
=> docs: Add COSMIC and fix broken contribution link

src/documents.c, src/documents.h, src/permissions.c, src/permissions.h, src/xdg-desktop-portal.c
And another small fix for a potential issue.
=> main: Exit early when permission store or document portal are missing

po/LINGUAS
Added support for Slovenian language.
=> Update LINGUAS - added sl (Slovenian)

document-portal/document-portal-fuse.c
Makes the entire file have a single style, and fixes a few variable declarations around.
=> document-portal/fuse: Cosmetics

.github/workflows/pages.yml
Hopefully no functional changes out of this.
=> pages: Update various actions

po/en_GB.po
See https://l10n.gnome.org/vertimus/xdg-desktop-portal/main/po/en_GB/
=> Update British English translation

src/settings.c, src/xdp-app-info-flatpak.c
g_build_filename() always transfer full
Add auto cleanup for Settings implementation
=> Fix some memory leaks

src/xdg-desktop-portal.c
This is the same as in the gnome portal.
Kill the portal with SIGHUP, it will run asan if it was built with asan.
=> Implement a signal handler to help with asan

.github/workflows/container.yml
This allows PRs to get through CI when they have changes in the required image.
=> ci: Use images from actor for pull requests

tests/notification.c, tests/test-portals.c
This test require unreleased code in a dependency. This fixes the build
=> Disable broken test

po/oc.po
=> Update Occitan translation

data/org.freedesktop.portal.GlobalShortcuts.xml
=> Update link to xdg shortcuts spec

po/ru.po
Hello, 
please add fully translated RU .po. The translated file is from GNOME's Damned Lies[1], was revied by me, I'm the coordinator. TY
[1] https://l10n.gnome.org/vertimus/2517/1021/31/
=> Add fully translated RU .po

tests/notification.c, tests/test-portals.c
They are still leaking but at least they pass now.
=> Fix the notification tests

tests/conftest.py
Otherwise we'll be stuck in the loop forever and it's not clear what's going on.
=> tests/conftest.py: Error out if xdp exited before exporting its bus

doc/_static/xdg.css, doc/conf.py
Based on https://github.com/flatpak/flatpak-docs/commit/29cd6f081cd921d25550eb7a5c4e99f792a5c321
=> conf: Enable html permalinks for headers on hover

doc/_static/xdg.css, doc/website/README.md
Unfortunately I can't get it to run locally and can't check it due to that.
=> Increase header sizes, use rem and make sure we use inter

document-portal/document-portal-fuse.c
The fuse lowlevel ops release vfunc says:
For every open call there will be exactly one release call (unless the
filesystem is force-unmounted).
Which means that if the filesystem is force-unmounted, there won't be a release call which can free a XdpFile allocated in open or create.
Introduce a list which keeps track of open files and cleans them up in the end so that we don't leak the memory. Technically this leak doesn't hurt because we will terminate anyway, but otherwise, asan will be very unhappy and we get random test failures.
=> document-portal: Track open files

data/org.freedesktop.host.portal.Registry.xml, doc/api-reference.rst, doc/fix-rst-dbus.py, doc/meson.build
=> Include host app registry in the docs

tests/__init__.py, tests/conftest.py, tests/test_background.py, tests/test_camera.py, tests/test_clipboard.py, tests/test_email.py, tests/test_filechooser.py, tests/test_globalshortcuts.py, tests/test_inhibit.py, tests/test_location.py, tests/test_notification.py, tests/test_openuri.py, tests/test_print.py, tests/test_remotedesktop.py, tests/test_settings.py
First two commits are very mechanical, the third one lets one override the dbus timeout using an environment variable.
=> Pytest improvements

tests/__init__.py, tests/test_document_fuse.py, tests/test_documents.py
Spotted by @whot in https://github.com/flatpak/xdg-desktop-portal/pull/1526
=> More small test improvements

tests/README.md
Explains that we have unit tests and integration tests, and a very high level overview of how each of them works.
=> tests/README: Explain the unit and integration test systems

src/dynamic-launcher.c
The g_desktop_app_info_new_from_keyfile function requires the the Exec line in the keyfile to be an executable (in the context of the current environment, so the portal). Flatpak apps do not have the executable on the host, but use `flatpak run`. The portal rewrites those Exec lines, but it did so after calling g_desktop_app_info_new_from_keyfile, so it would fail if whatever the Exec line specified was not a valid executable on the host.
Resolves: #1674
=> dynamic-launcher: Check Desktop file after AppInfo can rewrite Exec

RELEASE_HOWTO.md
The instructions were clear, but there were some minor gaps, which this attempts to fill.
=> Release procedure clarifications

src/xdp-portal-impl.c
meson.build still declares 2.72 as our minimum version.
Resolves: #1726
=> portal-impl: Add a fallback code path for GLib older than 2.76

src/screenshot.c, tests/test_screenshot.py
If the permission is neither unset, "yes" or "no" we ask but won't set the permission afterwards. Adjusts the text shown to the user for this case to be not misleading about what happens.
=> screenshot: Adjust texts when we are not setting permissions

po/sl.po
=> Update sl.po (Slovenian)

data/org.freedesktop.portal.DynamicLauncher.xml
And also slightly adjust the documentation for the name response.
Related: https://github.com/flatpak/xdg-desktop-portal/pull/1088
=> dynamic-launcher: Document the PrepareInstall icon response
