flatpak/xdg-desktop-portal

- src/xdg-desktop-portal.c
The symbol used to described handlers in the GVariant format string for
messages received from the implementating backend is 'o', so we need to
honor that when forwarding it to the sandboxed app, which expects that.
> Use the wrong type when forwarding the 'handle' parameter

- data/Makefile.am.inc
- data/org.freedesktop.impl.portal.AppChooser.xml
- data/org.freedesktop.portal.OpenURI.xml
- src/Makefile.am.inc
- src/open-uri.c
- src/open-uri.h
- src/xdg-desktop-portal.c
- src/xdg-desktop-portal.gresource.xml
Rename org.freedesktop.portal.AppChooser to org.freedesktop.portal.OpenURI
and redo the implementation along the same lines as the file chooser
portal. We use the new app chooser interface provided by the gtk
backend. More of the work is now done in the frontend: listing suitable
applications, and launching the chosen one. The backend provides a
simple chooser UI.
> Port the app chooser portal

- data/Makefile.am.inc
- data/org.freedesktop.portal.NetworkMonitor.xml
- src/Makefile.am.inc
- src/network-monitor.c
- src/network-monitor.h
- src/xdg-desktop-portal.c
Can just proxy the GLibNetworkMonitor functionality over dbus, and make it work in GLib
> Add a portal for  network connectivity

- data/Makefile.am.inc
- data/org.freedesktop.portal.NetworkMonitor.xml
- data/org.freedesktop.portal.ProxyResolver.xml
- src/Makefile.am.inc
- src/network-monitor.c
- src/network-monitor.h
- src/proxy-resolver.c
- src/proxy-resolver.h
- src/xdg-desktop-portal.c
This can probably reuse an existing libproxy backend.
> Add a portal for proxy information

- src/Makefile.am.inc
- src/open-uri.c
For now, it uses a hardcoded threshold of 5 consecutive executions to determine whether we want to hint the backend, suggesting it to use the default option right away.
This addresses issue https://github.com/flatpak/xdg-desktop-portal/issues/10
> Use permissions store to implement a simple 'remember latest choice' mechanism

- src/Makefile.am.inc
- src/documents.c
- src/documents.h
- src/file-chooser.c
- src/xdg-desktop-portal.c
The function to register a file in the documents portal is somewhat
long, and can be used by multiple portals. Break it out into its
own file.
> Split out document portal code

- COPYING
- data/org.freedesktop.impl.portal.AppChooser.xml
- data/org.freedesktop.impl.portal.FileChooser.xml
- data/org.freedesktop.impl.portal.Print.xml
- data/org.freedesktop.impl.portal.Screenshot.xml
- data/org.freedesktop.portal.FileChooser.xml
- data/org.freedesktop.portal.NetworkMonitor.xml
- data/org.freedesktop.portal.OpenURI.xml
- data/org.freedesktop.portal.Print.xml
- data/org.freedesktop.portal.ProxyResolver.xml
- data/org.freedesktop.portal.Request.xml
- data/org.freedesktop.portal.Screenshot.xml
- src/documents.c
- src/documents.h
- src/file-chooser.c
- src/file-chooser.h
- src/network-monitor.c
- src/network-monitor.h
- src/open-uri.c
- src/open-uri.h
- src/print.c
- src/print.h
- src/proxy-resolver.c
- src/proxy-resolver.h
- src/request.c
- src/request.h
- src/screenshot.c
- src/screenshot.h
- src/xdg-desktop-portal.c
- src/xdp-utils.h
Considering this project comes from flatpak one could assume that the license for this source code is LGPL 2+, but that would be just an assumption, so I think it would be great if we could specify this explicitly, so that people willing to ship this code knows what to use.
> Specify a software license

- src/request.c
- src/request.h
- src/xdp-utils.c
When we notice a name owner disappearing, clean up all outstanding
requests for that sender, and close dialogs.
> Clean up requests when sender dies

- doc/Makefile.am
We were continuously rebuilding the docs for the impl interfaces,
because I typoed their name in the file list.
> Fix a rebuild problem

- data/Makefile.am.inc
- data/org.freedesktop.impl.portal.Notification.xml
- data/org.freedesktop.portal.Notification.xml
- doc/Makefile.am
- doc/portal-docs.xml
- src/Makefile.am.inc
- src/notification.c
- src/notification.h
- src/xdg-desktop-portal.c
We want apps to (optionally) be allowed to send desktop-global notifications. Need a portal for this.
org.gtk.Notifications=talk is not the anwer, because that would be a way to give an app broad access to notifications in a static fashion. What we would like is a more dynamic portal that lets you give/take access to notification at runtime in a similar fashion to how it looks on e.g. iOS or android, or in fact how the GPS access stuff looks in gnome today (i.e. you'll see a list of apps in the control center and you can give individual apps access to it or not. Maybe we can even give multiple levels of access.).
> Need notification portal

- data/Makefile.am.inc
- data/org.freedesktop.impl.portal.Inhibit.xml
- data/org.freedesktop.portal.Inhibit.xml
- doc/Makefile.am
- doc/portal-docs.xml
- src/Makefile.am.inc
- src/inhibit.c
- src/inhibit.h
- src/xdg-desktop-portal.c
This lets sandboxed apps inhibit session status changes, such
as suspend or idle. This is the API that lets movie players
prevent the screensaver from kicking in halfway through the
movie.
> Add an inhibit portal

- data/org.freedesktop.impl.portal.FileChooser.xml
- data/org.freedesktop.portal.FileChooser.xml
- src/file-chooser.c
The OpenFile and OpenFiles methods were not really different
enough to justify the code duplication. Just add a boolean
option 'multiple' instead.
> Simplify filechooser portal api

- configure.ac
If the flatpak pkg-config file is not found, stop the configure process
with an error.
Fixes #48
> Error out if flatpak is not available

- src/file-chooser.c
Opening a chooser with a MIME content type filter gives an "invalid filter type: 1" error. This PR fixes the problem.
> Fix error using file filters with MIME content types.

- data/org.freedesktop.portal.Account.xml
- data/org.freedesktop.portal.Device.xml
- data/org.freedesktop.portal.FileChooser.xml
- data/org.freedesktop.portal.Inhibit.xml
- data/org.freedesktop.portal.NetworkMonitor.xml
- data/org.freedesktop.portal.Notification.xml
- data/org.freedesktop.portal.OpenURI.xml
- data/org.freedesktop.portal.Print.xml
- data/org.freedesktop.portal.ProxyResolver.xml
- data/org.freedesktop.portal.Screenshot.xml
- src/account.c
- src/device.c
- src/file-chooser.c
- src/inhibit.c
- src/network-monitor.c
- src/notification.c
- src/open-uri.c
- src/print.c
- src/proxy-resolver.c
- src/screenshot.c
I've looked a little at the portal's documentation and I think there isn't any documented way for a flatpak application to know which version of xdg-desktop-portal is installed in the system it's running on. I also think the apps can't define in their manifest which xdg-desktop-portal version they require to work properly.
This will be important to maintain compatibility with distros that don't upgrade often. For example, if Debian Stretch is released with xdg-desktop-portal 0.1 and camera support is added in version 0.2, applications using this feature will probably won't work in Debian and users won't know it until they try the app.
In Android they have solved [this way](https://developer.android.com/guide/topics/manifest/uses-sdk-element.html):
- Each Android release has an API version …
> Supporting different xdg-desktop-portal versions in apps

- README.md
The _xdg-desktop-portal-kde_ repository has been [moved](https://github.com/grulja/xdg-desktop-portal-kde/blob/master/README.md) to a new location.
> Update xdg-desktop-portal-kde url in README.md

- Makefile.am
- configure.ac
- src/Makefile.am.inc
- src/org.freedesktop.portal.Desktop.service.in
- src/xdg-desktop-portal.service.in
This puts xdg-desktop-portal in its own cgroup where systemd can
apply resource limits, etc. if configured to do so, and avoids
inheriting any non-standard execution environment that dbus-daemon
might have.
---
This branch also tidies up a minor build issue: the existing D-Bus .service file was cleaned up twice.
> Add a systemd user unit corresponding to the session service

- po/Makevars
Current encoding is latin-1. As all po files are UTF-8, I suggest to also use the UTF-8 encoding for Makevars.
> Encode po/Makevars in UTF-8

- src/notification.c
There shouldn't be a difference between the add- and remove-finish
functions, but still ...
> notification: Fix copy+paste error

- src/request.c
Fix for bug  #100, avoiding an infinite loop on collisions.
> If the random request ID creates a collision, pick a new random ID.

- src/open-uri.c
- src/request.c
- src/request.h
- src/xdp-utils.c
- src/xdp-utils.h
This makes OpenFile work in the sandbox by fixing various issues that were broken, and by rewriting paths in /app and /usr to the real location outside the sandbox.
> Make OpenFile work from sandbox

- data/org.freedesktop.impl.portal.AppChooser.xml
- src/open-uri.c
New mockups for the GNOME app chooser dialog require some more
data to display things properly. This commit adds the content type
and the filename.
> Send more data to the appchooser

- Makefile.am
- xdg-desktop-portal.pc.in
xdg-desktop-portal's .pc file is written as though it described a library that is linked to libflatpak and GLib, but in fact the only development files in xdg-desktop-portal are D-Bus introspection XML used as an interface description language.
This forces having Flatpak development files (libflatpak-dev or flatpak-devel depending on distribution) when developing against xdg-desktop-portal and checking for it with pkg-config, even though that is not actually necessary: it is true to say that xdg-desktop-portal depends on Flatpak and GLib *at runtime*, but .pc files are all about development dependencies rather than runtime dependencies.
The .pc file can also be installed in /usr/share/pkgconfig instead of /usr/lib/pkgconfig (or /usr/lib64 or /usr/lib/x86_64-linux-gnu or whatever the right …
> Alter pkg-config to reflect the architecture-independent development files

- src/email.c
The portal API pattern is inherently racy: The app receives the
response call with the handle of the Request object, but the
Response signal may have already been emitted from the portal
by the time the app has set up a listener for it. Normally, this
should not matter, since the portal api is expected to involve user
interaction - by the time the user is done with a dialog, the
app has certainly established its signal listener.
But, in the case of the email portal, we don't wait for the
'dialog' to be done, we simply launch the email client and
return, which can be rather quick.
To make this race less likely, at least complete the ComposeEmail
call before forwarding it to the backend.
> Make email portal race narrower

- data/org.freedesktop.portal.Email.xml
- src/Makefile.am.inc
- src/email.c
- src/open-uri.c
- src/xdp-utils.c
- src/xdp-utils.h
This not only fixes the issue of guaranteeing that the sandboxed app has access to the file it wants to attach, it also fixes the problem where /tmp inside the sandbox is different from /tmp outside the sandbox, since we do the necessary path translation here to make sure that the portal backend gets a path that it can access.
> Change the email portal api to take fds

- src/xdp-utils.c
This won't be useful if the path passed points to a directory not
reachable inside the sandbox, but it will at least allow opening
them in other cases where that might be the case.
https://github.com/flatpak/xdg-desktop-portal/issues/128
> xdp-utils: Also resolve file descriptors to paths for directories

- src/open-uri.c
When OpenFile is used to open a directory and either there's a default
application to handle file:// URIs, or only one appropriate application
is installed (e.g. Nautilus), we would hit a crash with the current code
since launch_default_for_uri() will be passed a NULL uri parameter.
This fixes that by ensuring that uri is always properly set at that point.
https://github.com/flatpak/xdg-desktop-portal/issues/129
> open-uri: Don't crash when opening files skipping the app chooser

- src/device.c
- src/open-uri.c
- src/request.h
Add extra checks to never do this when registering the URI with the
documents portal (for sandboxed handler) fails for any reason, and
report to the sandboxed caller accordingly when that happens.
https://github.com/flatpak/xdg-desktop-portal/issues/134
> open-uri: Don't ever pass a list of NULLs to g_app_info_launch_uris()

- data/org.freedesktop.impl.portal.Screenshot.xml
- data/org.freedesktop.portal.Screenshot.xml
- src/screenshot.c
This option indicates to the backend that it would
be useful to offer customization before taking a screenshot.
This is just a hint, backends may not have options or may
ignore the interactive option.
> screenshot: Add an 'interactive' option

- configure.ac
- data/Makefile.am.inc
- data/org.freedesktop.impl.portal.ScreenCast.xml
- data/org.freedesktop.impl.portal.Session.xml
- data/org.freedesktop.portal.ScreenCast.xml
- data/org.freedesktop.portal.Session.xml
- src/Makefile.am.inc
- src/call.c
- src/call.h
- src/request.c
- src/screen-cast.c
- src/screen-cast.h
- src/session.c
- src/session.h
- src/xdg-desktop-portal.c
- src/xdp-utils.c
This adds a screen cast portal, provided via org.freedesktop.portal.ScreenCast. A sample user illustrating how its used can be found here: https://gitlab.gnome.org/snippets/19 . A xdg-desktop-portal-gtk implementation (needing mutter 3.26 + https://bugzilla.gnome.org/show_bug.cgi?id=787715 ): https://github.com/jadahl/xdg-desktop-portal-gtk/commits/wip/screen-cast .
There are some things to note about it, and as is, it is not ready to be merged. More on that below.
1.
This is, as far as I can tell, the first portal API that introduces long lived sessions. I need this so that I can later couple a screen cast session with a remote desktop session. To summarize, doing remote desktop might (most likely) involve screen casting, but we should not pop up two portal dialogs; thus we need a …
> Add screen cast portal

- configure.ac
- data/Makefile.am.inc
- data/org.freedesktop.impl.portal.RemoteDesktop.xml
- data/org.freedesktop.impl.portal.ScreenCast.xml
- data/org.freedesktop.impl.portal.Session.xml
- data/org.freedesktop.portal.RemoteDesktop.xml
- data/org.freedesktop.portal.ScreenCast.xml
- data/org.freedesktop.portal.Session.xml
- src/Makefile.am.inc
- src/call.c
- src/call.h
- src/remote-desktop.c
- src/remote-desktop.h
- src/request.c
- src/screen-cast.c
- src/screen-cast.h
- src/session.c
- src/session.h
- src/xdg-desktop-portal.c
- src/xdp-utils.c
This PR adds a remote desktop portal. By itself it only provides remote control of input devices; combined with the screen cast portal (#122), it can also provide screen sharing in the same session. The branch contains the commits from #122 because there doesn't seem to be a way to pretend the first three are separate, so please refer to #122 for those.
> Add remote desktop portal

- src/documents.c
Make use of new add_named_full() function where we can specify with flags whether
the document portal should return real path to file we have access to or if it
should return path to fuse mountpoint
> Return real path when saving files we have access to

- src/xdp-utils.c
This is a port of https://github.com/flatpak/flatpak/pull/1063
(And really we should figure out how to share this security-sensitive
code between the two projects...)
There's an oustanding bubblewrap PR where we'd like to change how we set up the
rootfs; a side effect of this will be that /newroot disappears from the /proc
links: bubblewrap pull 172.
> Handle bubblewrap dropping /newroot prefix

- data/org.freedesktop.impl.portal.RemoteDesktop.xml
- data/org.freedesktop.portal.RemoteDesktop.xml
- src/remote-desktop.c
This is so that an end to a continuous axis motion can be reported
(equivalent of lifting a finger) meaning clients can turn this into a
kinetic scroll.
> remote-desktop: Add 'finish' option to axis events

- data/org.freedesktop.portal.ScreenCast.xml
SelectSources() actually looks for the key "types", not "type".
As pointed out by @grulja
> screencast: Document correct vardict option

- Makefile.am
This wasn't set up when it was copied from Flatpak.
> build: Run install-test-data-hook as intended

- src/xdp-utils.c
g_variant_get (..., "s", ...) copies the string out of the variant.
g_variant_get (..., "&s", ...) borrows it from the variant, which is
what we want here.
Signed-off-by: Simon McVittie <smcv@collabora.com>
> utils: Don't leak names whose ownership changed

- src/screen-cast.c
We wait until we get the last object from the registry by looking at
a sync reply with the sequence number in registry_sync_seq. Add the
missing sync request to make this work.
> screen-cast: add missing sync request

- src/file-chooser.c
Don't crash when a save-file backend call fails. We'd do so because
we'd compare with and pass around uninitialized data if _finish() call
failed. Avoid this as done elsewhere by initializing the variables
passed to the _finish() function.
> file-chooser: Handle save-file backend failure

- src/xdp-utils.c
I've been working on [improving containers support in the reference implementation of D-Bus](https://bugs.freedesktop.org/show_bug.cgi?id=100344).
This branch contains some refactoring on the way to that:
* Make more use of constants
* Make it clearer that the hash table currently named app_infos is indexed by the unique name of a D-Bus peer (because I'm going to add a parallel hash table indexed by the fd.o#100344 container ID)
* Use a tagged union to distinguish between Flatpak and other container technologies, and generalize the storage of technology-specific metadata a bit (this might be useful for #155 and #136)
It also includes #162.
> Refactor in preparation for using org.freedesktop.DBus.Containers1

- data/org.freedesktop.impl.portal.RemoteDesktop.xml
- data/org.freedesktop.portal.RemoteDesktop.xml
- src/remote-desktop.c
The devices are bits in a bitmask, but were numbered 1, 2 and 3, both
in the API documentation and in the implementation. The order in the
implementation was also incorrect.
> remote-desktop: Correct device type values

- src/open-uri.c
When we have a sandboxed handler, we try to register
the uri with the document portal to ensure that the
handler can access it. But this only makes sense if
the uri is a file: one.
This was causing failures when opening http: uris
via the portal with a sandboxed epiphany.
See https://github.com/flatpak/xdg-desktop-portal/issues/173
> Don't register http: uris

- README.md
Use the new docs URL as mentioned in
https://github.com/flatpak/xdg-desktop-portal/issues/138#issuecomment-376379696
> README: Fix docs link

- document-portal/document-portal-fuse.c
- document-portal/document-portal.c
- src/xdp-utils.c
- src/xdp-utils.h
This adds support for snaps, based on the code in https://github.com/flatpak/xdg-desktop-portal/pull/136 by @jhenstridge. I did not actually test this, so it needs testing before it can be commited.
This PR includes the changes from https://github.com/flatpak/xdg-desktop-portal/pull/154, but we should probably land those separately first.
This should handle the basics of portals, but there are two things still missing:
* xdp_get_app_info_from_pid() needs support to look up a snap AppInfo from the pid
* app_has_file_access() in document-portal.c currently only supports flatpak, it would be interesting to have a version of this for snaps too.
> Support snap

- document-portal/document-portal.c
- src/email.c
- src/open-uri.c
- src/xdp-utils.c
- src/xdp-utils.h
As discussed in https://github.com/flatpak/xdg-desktop-portal/issues/167 using O_PATH to pass proof of access to a file is not good enough for e.g. snap, as it only means the sandbox can see the pathname, not that it can e.g. open it. So, if the fd is not O_PATH we use the open flags to detect if the file should be writable or not.
For directories we still use O_PATH because there is no way to prove writability to a directory. However, AddNamed*() is only callable from the host, so that is not really a problem.
We still support O_PATH for host and flatpak callers, because those  are safe and there are still code out there using this.
> Support non-O_PATH fds for adding existing files

- src/open-uri.c
The warning message is wrong since we're not updating the permission
store, but accessing it, at that point so we need to fix that. Besides
the warning message should only shown when the error is other than
NOT_FOUND, since not having a entry recorded in the desktop-apps table
for a particular content-type is a perfectly fine scenario.
> OpenURI: Fix misleading warning when accessing the permission store

- src/open-uri.c
If a threshold is set for a given content-type/schema and app ID in the
permission store, we should make the decision on whether to show the
app chooser dialog or not based only on whether such threshold has been
reached by consistently selecting the same app a big enough amount of
consecutive times, not based on whether we're opening a directory or
a HTTP/HTTPs URI (only cases when we currently might skip the dialog).
If a threshold is not set (this is the default unless the permission store
has been altered with an external tool), the current behaviour is kept
and the dialog will still be skipped for those special cases.
https://github.com/flatpak/xdg-desktop-portal/issues/149
> OpenURI: Don't skip the dialog based on content type if a threshold is set

- src/remote-desktop.c
- src/screen-cast.c
- src/session.c
Sending bogus arguments to org.freedesktop.portal.ScreenCast.CreateSession (and probably org.freedesktop.portal.RemoteDesktop.CreateSession) caused xdg-desktop-portal to crash.
See https://github.com/flatpak/xdg-desktop-portal/issues/186
> Handle incomplete create session gracefully

- data/org.freedesktop.portal.OpenURI.xml
- doc/Makefile.am
- doc/portal-docs.xml.in
This is a little different, since the flatpak portal actually lives in the flatpak repository, so we include it here from its installed location in /usr/share/dbus-1/interfaces/
> Include the flatpak portal docs

- data/org.freedesktop.impl.portal.Screenshot.xml
- data/org.freedesktop.portal.Screenshot.xml
- src/screenshot.c
This will be used to implement a color picker for
sandboxed apps. The implementation here uses a
new gnome-shell D-Bus API.
> screenshot: Add a PickColor method

- configure.ac
PipeWire 0.2.x changed API and is not ABI compatible with 0.1.x versions. We should require latest one as it's probably the one used at this moment and in near future. Also minor problem is that PW 0.2.0 and 0.2.1 were missing to bump version in library name, thus libpipewire-0.2 exists with PW 0.2.2 and newer.
> Depend on current PipeWire library

- README.md
The "Design Considerations" section used lines that were longer than 80 columns in the source, but still had paragraphs broken into multiple (long) lines, making the file especially hard to read on the terminal. Re-wrapped the lines to <= 80 columns, with no content changes or alterations of the rendered formatting.
> Format README.md source to 80-column width

- data/org.freedesktop.portal.NetworkMonitor.xml
- src/network-monitor.c
GetStatus lets us avoid multiple roundtrips to get all the values.
CanReach lets us implement g_network_monitor_can_reach().
> network monitor: Add GetStatus and CanReach methods

- document-portal/document-portal-fuse.c
When creating nodes we forgot to free them, so inodes would never go away, even when the kernel told us it forget about them. 
This causes issues when re-creating forgotten files, such as #195, which hits the TODO in xdp_inode_create_file():
```    
if (truncate)
{
/* TODO: Handle extra truncate for existing file */
errno = ENOSYS;
```
We should really fix the TODO, but with the proper inode refcounting
we avoid hitting it in this case, because the first lookup of the now
deleted file will cause the kernel to forget() the inode, which
deletes the pre-existing XdpInode.
Fixes #195
> document-portal: Fix XdpInode leak

- data/org.freedesktop.impl.portal.Inhibit.xml
- data/org.freedesktop.portal.Inhibit.xml
- src/inhibit.c
- src/request.c
- src/session.c
- src/session.h
For now, this just includes the screensaver-active
state, since several applications are using this.
More can be added.
We can avoid leaking this information to everybody
by putting a CreateMonitor request in front of it.
> inhibit: Add session state monitoring

- src/network-monitor.c
Vardict entries are of type {sv}, so wrap the actual value in a variant.
> network-monitor: Fix variant type

- src/network-monitor.c
The ::network-changed signal is emitted when the network configuration
changes, which doesn't necessarily mean a change of network availability
or connectivity. For example connecting to a VPN doesn't usually change
the general online state, but as additional services become available,
clients may want to retry previously failed connection attempts.
To support this use case in the portal implementation, simply relay
the "native" network monitor's ::network-changed signal instead of
listening for property changes.
> network-monitor: Use ::network-changed for change notifications

- Makefile.am
- configure.ac
Simplify the existing --enable-coverage configure option
and add a coverage target to generate coverage testing for
the testsuite. The generated html ends up in the coverage/
directory.
> Add lcov support

- src/xdg-desktop-portal.c
This PR is related to some crash reports we've been seeing on Ubuntu where xdg-desktop-portal segfaults during start-up.  In short, there is a timeout trying to activate xdg-desktop-portal-gtk that leads to export_portal_implementation() being called with a NULL skeleton argument.  Here are the logs from one occurrence of the crash:
xdg-desktop-por[3113]: Failed to create file chooser proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Timeout was reached
xdg-desktop-por[3113]: g_dbus_interface_skeleton_set_flags: assertion 'G_IS_DBUS_INTERFACE_SKELETON (interface_)' failed
xdg-desktop-por[3113]: invalid (NULL) pointer instance
xdg-desktop-por[3113]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
xdg-desktop-por[3113]: …
> desktop-portal: don't attempt to export NULL GDBusInterfaceSkeletons

- data/org.freedesktop.portal.Settings.xml
- src/Makefile.am.inc
- src/request.c
- src/settings.c
- src/settings.h
- src/xdg-desktop-portal.c
This is a minimal portal that effectively just replaces XSettings on Wayland without requring DConf access.
@grulja @aleixpol - I'd like your input on if you can use this to replace your `--filesystem=xdg-config/kdeglobals:ro` permission also.
> Add Settings portal

- configure.ac
- src/Makefile.am.inc
- src/fc-monitor.c
- src/fc-monitor.h
- src/settings.c
This is not a gsetting, so we treat it separately.
To make things easy for clients, we put it in a
fake org.gnome.fontconfig namespace.
The fontconfig monitor code here is copied from
gnome-settings-daemon.
> settings: Support the fontconfig timestamp

- data/org.freedesktop.portal.FileChooser.xml
Properties which are send as byte array need to be null-terminated.
> Add note about byte array properties in filechooser portal

- data/org.freedesktop.impl.portal.AppChooser.xml
- data/org.freedesktop.impl.portal.FileChooser.xml
- data/org.freedesktop.impl.portal.Print.xml
- src/file-chooser.c
- src/open-uri.c
- src/print.c
GNOME has lockdown settings for printing, file saving and
application handlers. Add 'disabled' properties to the
corresponding portal backend interfaces, and respect these
in the frontends by returning 'not allowed' errors.
To explain the design I ended up with here:
I started to add the lockdown in the backend (returning errors from portal backend calls),
but it turns out that the openuri portal frontend has shortcuts and doesn't use a backend
at all, some of the time. To address this, I moved the lockdown handling to the frontend.
It is a good fit with the other permission handling that happens in the frontend.
To keep the desktop-specific implementation (GNOME lockdown settings) out of the
frontend, I added 'disabled' properties to the backend interfaces in question, which
the frontend …
> Implement lockdown for some portals

- data/org.freedesktop.impl.portal.AppChooser.xml
- src/open-uri.c
In the OpenURI portal, monitor for application changes,
and update the backend. This requires a new UpdateChoices
method in the AppChooser interface.
> Monitor application changes

- document-portal/permission-db.c
We can store a NULL PermissionDbError (which is just an alias for
GVariant) in main_updates, as a "white-out" that indicates that an
entry has been removed. Callig g_variant_unref() on NULL is considered
to be a programming error.
> Document portal: Don't raise a critical when removing entries

- tests/test-doc-portal.c
Distribution autobuilders sometimes use a hardened OS configuration that
does not allow module loading or FUSE; in particular, this is the case
in Debian. In this environment, global setup does not complete,
`documents` is NULL and this test would segfault. Skip the test and rely
on installed-tests to cover it instead.
> test-doc-portal: Skip all tests if FUSE isn't supported

- data/Makefile.am.inc
- data/org.freedesktop.impl.portal.AppChooser.xml
- data/org.freedesktop.impl.portal.FileChooser.xml
- data/org.freedesktop.impl.portal.Lockdown.xml
- data/org.freedesktop.impl.portal.Print.xml
- doc/Makefile.am
- doc/portal-docs.xml.in
- src/Makefile.am.inc
- src/device.c
- src/device.h
- src/file-chooser.c
- src/file-chooser.h
- src/location.c
- src/location.h
- src/open-uri.c
- src/open-uri.h
- src/print.c
- src/print.h
- src/xdg-desktop-portal.c
Redo lockdown properties as a separate interface, to avoid problems with the lack of backends for some portals that may grow lockdown.
> Lockdown, part 2

- src/notification.c
We want to use the fact that there are permissions in the
permission store for an app to hide or show the corresponding
row in the control-center. Basically, we want the permission
store to record which apps have used this portal. So, make
the notification portal write back a "yes" when the app is
using it.
> notification: Write back permissions

- document-portal/document-portal-fuse.c
If it's not set, the default value is 0 and Qt fails to detect whether the mounted file exists or not.
> Document portal: set st_nlink to 1 for documents

- src/email.c
- src/file-chooser.c
- src/remote-desktop.c
- src/screen-cast.c
- src/xdp-utils.c
- src/xdp-utils.h
This lets us do validation depending on the values
of other options, which is sometimes necessary.
Update all callers.
> Pass all options to validation functions

- data/org.freedesktop.impl.portal.FileChooser.xml
- data/org.freedesktop.portal.FileChooser.xml
- src/file-chooser.c
This will allow xdg-desktop-portal-gtk to call
gtk_file_chooser_set_filter() to make file filters not suck to use.
https://gitlab.gnome.org/GNOME/gtk/issues/1492
> file-chooser: Add support for proxying current_filter

- src/notification.c
These are small, and will get cleaned up eventually,
but there's no reason not to remove them when we don't
need them anymore.
> notification: Don't leave temp files around

- data/org.freedesktop.impl.portal.Inhibit.xml
- data/org.freedesktop.portal.Inhibit.xml
- src/inhibit.c
This will be used to inform monitoring applications about
the impending end of the session.
> inhibit: Add session state to the StateChanged signal

- data/org.freedesktop.impl.portal.ScreenCast.xml
- data/org.freedesktop.portal.ScreenCast.xml
- src/screen-cast.c
Used to let the portal user decide whether to hide, embed or side
channel the cursor sprite of a screen cast.
Hiding it means it won't be visible. Embedding it means it'll be
embedded into the screen cast video stream buffers. Side channelling it
means it will be sent as PipeWire stream metadata, leaving the stream
video content itself free of cursor sprites.
> screen-cast: Add cursor modes

- src/Makefile.am.inc
- src/pipewire.c
- src/pipewire.h
- src/remote-desktop.c
- src/screen-cast.c
Quoting the last commit:
```
screen-cast: Roundtrip after setting permissions
Otherwise we can't be sure the pipewire daemon has seen them.
```
In general, the permissions we set might not have any effect if don't make sure the server has processed them before handing over the fd.
> Rountrip after PipeWire screen past permissions are set

- src/location.c
This would have caused problems on architectures where %li is not 64
bits, like 32-bit ARM.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
> location: Fix incorrect format string for printing a gint64

- src/settings.c
This is glib 2.50 or higher, which doesn't exist on xenial.
> settings: Don't use G_VARIANT_BUILDER_INIT

- configure.ac
- data/Makefile.am.inc
- data/org.freedesktop.impl.portal.Background.xml
- data/org.freedesktop.portal.Background.xml
- doc/Makefile.am
- doc/portal-docs.xml.in
- src/Makefile.am.inc
- src/background.c
- src/background.h
- src/flatpak-instance.c
- src/flatpak-instance.h
- src/xdg-desktop-portal.c
- src/xdp-utils.c
- src/xdp-utils.h
Implement a facility that monitors running flatpaks,
and notifies the user if they run in the background.
Add a permission table to store users responses
persistently.
The platform-dependent parts of this (getting the
state of running applications, and notifying the user)
are handled by a portal backend.
There is currently no application API.
> Implement a background monitor

- data/Makefile.am.inc
- data/org.freedesktop.portal.GameMode.xml
- doc/Makefile.am
- doc/portal-docs.xml.in
- src/Makefile.am.inc
- src/gamemode.c
- src/gamemode.h
- src/request.c
- src/xdg-desktop-portal.c
- src/xdp-utils.c
- src/xdp-utils.h
This is to resolve flathub/com.valvesoftware.Steam#77 where the main problem is that we need to resolve the process id from within the flatpak so that GameMode can work with the correct one: 
Add a new portal so that GameMode service can be accessed from within the sandbox. GameMode expects to get the process id (pid) of the game so it can:
- track the lifetime of the game
- modify process parameters (nice level, scheduler policy, ...)
- resolve the executable name and trigger configured actions
Since processes inside the sandbox run in a separate pid namespace sending the client pid obtained via getpid(2) won't work. Getting the pid via the D-Bus connection will result in getting the pid of the dbus proxy. According to pid_namespaces(7) process ids will be translated by the kernel when …
> gamemode: add new portal for GameMode access

- configure.ac
- data/org.freedesktop.portal.Camera.xml
- src/Makefile.am.inc
- src/background.c
- src/camera.c
- src/camera.h
- src/device.c
- src/device.h
- src/permissions.c
- src/permissions.h
- src/pipewire.c
- src/pipewire.h
- src/request.c
- src/screen-cast.c
- src/xdg-desktop-portal.c
This adds a camera portal. It also includes fixes to the screen-cast portal, including one that will make it work with pipewire-0.2.6.
The portal works the following way:
There is a method `AccessCamera`, that will query the permission store and maybe the `Access` to query the user.
There is a method `OpenPipeWireRemote` that will open a pw_remote file descriptor. This method will only work if "yes" is already in the permission store. The PipeWire remote will be prepared with portal related metadata using `pipewire.access.portal.*` properties. All permissions will be set to `---` meaning no nodes will be available via the remote initially. PipeWire daemon side, there is a `module-portal` that then will handle keeping permissions up to date by querying and listening to the permission …
> Camera portal

- configure.ac
- doc/Makefile.am
The current build scripts look in $datadir for Flatpak interface
descriptions. This does not work if these files are installed under
/usr/share (the default) and the package's $datadir is located under
/usr/local/share (also the default). With the patch, the Flatpak
directory is either autodetected from pkg-config or set on configure's
command line.
Signed-off-by: Thomas Zimmermann <tzimmermann@suse.de>
> configure.ac: Make Flatpak interface directory configurable

- data/org.freedesktop.portal.GameMode.xml
- src/gamemode.c
- src/xdp-utils.c
GameMode 1.4 added a set of new APIs that mirror the existing ones
but where once process can act on behalf of the another. The only
difference of the new function calls to the existing one is the
additional "requester" argument (a process id). In case of faltpak
this new pid argument also needs to be to be mapped from the pid
namespace of the sandbox to the pid namespace of the host.
> Add support for GameMode 1.4 APIs

- src/request.c
The "Background" portal vardict option is not handled. This way,
requests won't consider their "options".
Currently, while calling "RequestBackground" a user would get the
error bellow:
Support for org.freedesktop.portal.Background missing in src/request.c:315
> request: Hardcode vardict options of the "Background" portal

- src/screen-cast.c
Without this, the permissions for the parent node of the node factory are
missing. Use append_parent_permissions() here as well to fix this.
Fixes #342
> screen-cast: fix permission setup

- src/xdp-utils.c
Fixes #352
Because xdg-desktop-portal is kinda hard to set up and run, this is a low-effort **untested** merge request. No warranty. But it looks right. We might need to keep info_fd open until we're done with the GMappedFile that's using it -- not sure -- but at this point we are already done with it, so should be OK.
> Fix leak of .flatpak-info fd

- document-portal/document-portal-fuse.c
- tests/Makefile.am.inc
- tests/test-doc-portal.c
Some CI pipelines do the build and `make check` as root in a container,
with CAP_DAC_ADMIN, which means /dev/fuse is writable; but if we
do not have appropriate permissions in the inheritable set (notably
CAP_SYS_ADMIN) then we cannot actually mount FUSE filesystems.
> test-doc-portal: Check for FUSE support more thoroughly

- src/background.c
Only warn once if we don't find the shell api.
Closes: https://github.com/flatpak/xdg-desktop-portal-gtk/issues/215
> background: Don't spam the logs

- data/Makefile.am.inc
- data/org.freedesktop.impl.portal.Secret.xml
- data/org.freedesktop.portal.Secret.xml
- src/Makefile.am.inc
- src/request.c
- src/secret.c
- src/secret.h
- src/xdg-desktop-portal.c
This adds a portal interface to provide sandboxed applications with master secret to locally encrypt credentials.  It works as follows: the application first creates a pipe, sends the write end to the portal, and the portal sends back a secret value through the FD. That way, we can avoid any transport encryption.
If the master secret doesn't exist in keyring, the portal generates a random secret. This step needs to be done with a standard conforming crypto library as the secret is used for encryption. Therefore the backend implementation resides in gnome-keyring.
See also:
- https://gitlab.gnome.org/GNOME/libsecret/merge_requests/6
- https://gitlab.gnome.org/GNOME/gnome-keyring/merge_requests/18
Fixes #14
> Add a secret portal

- src/settings.c
GNOME Boxes needs access to input-sources so it can propagate the
host default sources to virtual machines that are automatically
created throughout our express-install technology.
See https://gitlab.gnome.org/GNOME/gnome-boxes/blob/master/src/unattended-installer.vala#L684
____________________
I spoke briefly to @matthiasclasen about this in irc #boxes. He said that he was open to discussing the addition of input-sources settings.
> settings: Expose "org.gnome.desktop.input-sources"

- document-portal/permission-db.c
g_file_load_contents returns G_IO_ERROR/G_IO_ERROR_NOT_FOUND if the database doesn't exist.
This only becomes an issue on the NFS path because the non-NFS path doesn't use this call.
Add error handling for this domain/error combination so xdg-document-portal doesn't fail to start.
Fixes #369
> Handle file not found error from g_file_load_contents

- data/Makefile.am.inc
- data/org.freedesktop.impl.portal.Wallpaper.xml
- data/org.freedesktop.portal.Wallpaper.xml
- doc/Makefile.am
- doc/portal-docs.xml.in
- src/Makefile.am.inc
- src/request.c
- src/wallpaper.c
- src/wallpaper.h
- src/xdg-desktop-portal.c
The implementation is at https://github.com/flatpak/xdg-desktop-portal-gtk/pull/216
It basically has two similar APIs:
**SetWallpaper** and **ShowWallpaperPreview**.
SetWallpaper requires permissions and enables apps to set a wallpaper without any UI (after its been authorized).
ShowWallpaperPreview doesn't interact with the permission store because we assume the user is indicating consent when clicking in the dialog.
Design discussions were held in https://github.com/flatpak/xdg-desktop-portal/issues/335
PS.: Many of the UI labels refer to Wallpapers as Backgrounds. "Backgrounds" is the adopted terminology in GNOME but I went for "Wallpaper" for the portal code part to avoid confusion with the "Backgrounds" portal/monitor that does something else.
> Add Wallpaper portal

- data/org.freedesktop.portal.GameMode.xml
- src/gamemode.c
- src/xdp-utils.c
- src/xdp-utils.h
I created a patchset adding a set of pidfd based D-Bus APIs to gamemode. See PR FeralInteractive/gamemode#173 for more details but the gist of it is that we can avoid the costly mapping operation from the container pidns to the host pidns.
> gamemode: add pidfd based API

- data/org.freedesktop.portal.OpenURI.xml
- src/open-uri.c
Add an OpenDirectory method that opens the directory
containing a file in the file browser. The use case
for this is e.g. opening a downloads directory.
See https://github.com/flatpak/xdg-desktop-portal/issues/95
> openuri: Add an open directory method

- document-portal/document-portal.c
When we fail to load the database, point out the file.
> document portal: Make error message more helpful

- document-portal/document-portal-fuse.c
- document-portal/document-portal.c
Make the document portal exit when the fuse filesystem
is unmounted externally. This should fix 'suddenly stops
working' issues after suspend.
> Make document portal exit on unmount

- autogen.sh
Otherwise building will fail when creating the docs with some missing
files.
```
warning: failed to load external entity "/builddir/xdg-desktop-portal/doc/portal-org.freedesktop.portal.Flatpak.UpdateMonitor.xml"
/builddir/xdg-desktop-portal/doc/portal-docs.xml:116: element include: XInclude error : could not load /builddir/xdg-desktop-portal/doc/portal-org.freedesktop.portal.Flatpak.UpdateMonitor.xml, and no fallback was found
```
> build: Add checks for new enough Flatpak version

- data/org.freedesktop.impl.portal.FileChooser.xml
- data/org.freedesktop.portal.FileChooser.xml
- src/file-chooser.c
Adds definition and implementation of org.freedesktop.portal.FileChooser::SaveFiles
The general idea here is to enable applications saving multiple files at once. This is typically done by opening a Save file chooser in "select a folder" mode, but that's not possible to implement securely for sandboxed applications. To address this, the `SaveFiles` method allows the application to specify all of the file names that need to be saved, then forwards these to the implementation portal to have it open a Save file chooser in folder mode. When a folder is selected, the portal sends back a list of absolute URIs being the folder selected joined with the names of each of the given files. The application then is returned a list of files it can write to.
Fixes #158
> Implementation of org.freedesktop.portal.FileChooser::SaveFiles

- data/org.freedesktop.portal.Email.xml
So that email clients can support Flatpak portals.
> doc: Document mailto: URI scheme

- document-portal/xdg-permission-store.c
- tests/openuri.c
- tests/test-permission-store.c
The Set call is stripping one level of GVariant wrapping
from the data, but SetValue wasn't, leading to extra
wrapping accumulating in the database.
> Permission store data

- data/org.freedesktop.portal.FileTransfer.xml
- doc/Makefile.am
- doc/portal-docs.xml.in
- document-portal/Makefile.am.inc
- document-portal/document-portal.c
- document-portal/document-portal.h
- document-portal/file-transfer.c
- document-portal/file-transfer.h
- tests/openuri.c
This branch adds a "FileTransfer" portal to the document portal binary. It can be used to implement dnd and copy/paste. By using the portal as a side-channel to transfer the files (while exporting them as-needed).
This works, and https://gitlab.gnome.org/GNOME/gtk/merge_requests/321 has corresponding gtk changes. Future todo: better handling for directories.
> File transfer

- document-portal/permission-store.c
- document-portal/xdg-permission-store.c
- src/open-uri.c
- tests/backend/appchooser.c
- tests/openuri.c
- tests/test-portals.c
Collect all the code that handles the 'shall we open a dialog'
policy in one place. And tweak the rules we apply slightly, with
the goal of being less annoying by default, while still supporting
paranoid use cases.
By default, we skip the app chooser and directly launch the
default handler for http and inode/directory requests. We also
skip the app chooser if there is only one choice.
Lastly, we skip the app chooser if the last choice he been
selected often enough by the user (the threshold we use here
is 3).
The application can override these defaults by passing the
'ask' open with the OpenURI request. If that option is present,
we always show the app chooser.
The user can override everything by setting the threshold value
in the permission store to the special value 2147483647 …
> open-uri: Revamp the policy

- data/org.freedesktop.portal.Email.xml
Older gdbus-codegen fail on the fancy quotes. Also try making a CI build on xenial to test this.
> Fix old glib

- tests/location.c
Some CI systems do their builds in a container or chroot that does not
have a D-Bus system bus, and we can't expect Geoclue to work in that
situation. Ideally the location portal would report this as an error, but
at the moment the test just hangs if we cannot connect to the system bus.
> tests: Skip Location tests if we have no D-Bus system bus

- tests/Makefile.am.inc
- tests/camera.c
- tests/filechooser.c
- tests/openuri.c
- tests/print.c
- tests/utils.c
- tests/utils.h
On the client side, functions like xdp_impl_lockdown_set_disable_printing
initiate an asynchronous property-set operation but do not wait for it
to finish. As a result, if we want other modules to have caught up with
the change, we have to wait for the set to succeed.
Fixes: #394
---
I'm not 100% sure that this fixes the race completely (I'd have to draw a sequence diagram to be sure), but it certainly helps.
> tests: Fix race condition in various Lockdown tests

- Makefile.am
- tests/Makefile.am.inc
- tests/backend/Makefile.am.inc
- tests/test-portals.c
* tests: Install test-backends
This is necessary for test-portals to work when run as an installed-test.
* tests: When installed, look for executables in libexecdir
They won't normally be in the PATH when installed.
* tests: Install test.portal for installed-tests
Otherwise, when running installed-tests, xdg-desktop-portal will
find a real installed backend such as xdg-desktop-portals-gtk (if any),
rather than using the intended test backend. Fixes: #431
> Fix test-portal when installed

- data/org.freedesktop.portal.Documents.xml
- document-portal/document-enums.h
- document-portal/document-portal-fuse.c
- document-portal/document-portal-fuse.h
- document-portal/document-portal.c
- document-portal/document-portal.h
- document-portal/document-store.h
- document-portal/file-transfer.c
- src/xdp-utils.h
- tests/Makefile.am.inc
- tests/session.conf.in
- tests/test-doc-portal.c
- tests/test-document-fuse.py
- tests/test-document-fuse.sh
- tests/test-permission-store.c
This reimplements the fuse backend in a much nicer way. It also adds a new flag to export and entire directory, bumping the portal version to 4. I also added a new testsuite for the fuse implementation.
This is not quite finished, outstanding issues are:
* The code to re-use existing document ids is busted for directories.
* I need to actually test this live with existing apps to make sure we don't regress.
* There is a possibility the the new implementation run out of fd:s easier, I need to do some testing on this, especially on older distro versions with lower max-fd settings.
* We're currently not doing *anything* about symlinks in the directory support, which means that they relative symlinks in the exported directories might break. This needs more consideration to see if we can solve …
> New document-portal fuse backend with directory support

- document-portal/org.freedesktop.portal.Documents.service.in
- src/org.freedesktop.portal.Desktop.service.in
Snapd's confinement rules grant access to xdg-desktop-portal through an AppArmor rule that uses the `peer=(label=unconfined)` restriction to indicate that we expect the service to be running outside of the sandbox.  This allows access if xdg-desktop-portal is already running, but fails if it needs to be activated since dbus-daemon doesn't know what security label the service will run as, as described here:
https://dbus.freedesktop.org/doc/dbus-specification.html#message-bus-starting-services-apparmor
This branch adds the `AssumedAppArmorLabel=unconfined` key to the service files.  The key is ignored on systems that are not using AppArmor, or where dbus-daemon has been compiled without AppArmor mediation support, so it probably isn't worth making this optional.
> src, document-portal: add AssumedAppArmorLabel key to D-Bus service files

- src/background.c
`flatpak_instance_get_app` returns NULL for sandboxes that don't have an application, but `get_one_app_state` expects a non-NULL app_id. This causes a segfault if a flatpak runtime is being run directly (eg. "flatpak run org.freedesktop.Platform/x86_64/19.08") during `check_background_apps`.
Fixes: 0ad363fe6d8 ("background: Monitor running apps")
Closes: #433
> background: Skip check where app_id is NULL

- src/xdp-utils.c
Toolbox [1] containers are development environments whose primary goal
isn't secure containment of processes, but to offer a safe haven for
development without touching the host operating system. This is
particularly useful on OSTree based systems like Fedora Silverblue,
where it's significantly difficult to set up a development prefix
directly on the host OS. These containers are rootless OCI containers,
not Flatpak containers, and are designed to blur the divide between the
host and the container as much as possible - full access to $HOME, the
D-Bus sockets, the Wayland and X11 sockets, host network access, no
PID namespace, etc..
Therefore, conceptually, running an application inside a Toolbox
container is the same thing as running it on the host.
Identifying the runtime environment …
> utils: Recognize applications in Toolbox containers from the host

- src/xdp-utils.c
This was freeing the value before returning it.
This was noticed by jhenstridge in https://github.com/flatpak/xdg-desktop-portal/pull/443
> utils: Fix use-after-free in xdp_get_app_info_from_pid()

- configure.ac
Check whether the Flatpak interfaces directory is correctly set in the
configure file rather than failing at the build stage.
Closes: #450
> configure.ac: Report early when flatpak is not installed

- configure.ac
When building from git, we need a newer flatpak, or we need to disable the docs. The default for the building the docs being "automatic" we need to check whether there is a interfaces file already provided for us (as it would be for a tarball), otherwise we need to check whether we can find one.
> Check flatpak interfaces file if needed

- src/Makefile.am.inc
- src/documents.c
Rather than documenting a magic number, use the symbolic names as
defined in an enum.
> documents: Use symbolic names for flags

- data/org.freedesktop.impl.portal.FileChooser.xml
- data/org.freedesktop.portal.FileChooser.xml
- src/file-chooser.c
Add a new directory option to "OpenFile" to allow selecting directories
instead of files.
> file-chooser: Add "directory" option

- document-portal/document-portal-fuse.c
- tests/test-document-fuse.py
This has some work that tries to keep down the nr of fds used in the document portal.
This was causing some issues when building on ubuntu, as it needed > 4096 fds in the fuse stress test.
> Try to use less file descriptors in document portal

- tests/test-document-fuse.sh
This was failing the ppa build which has not fuse
> tests: Disable fuse tests if fuse is not available

- src/open-uri.c
Unless the user has "always ask" set in the permissions, or the application requested for the application chooser to be shown, always open browser (or other internet) links and directories in the default application.
> Use system default browser when opening links

- data/org.freedesktop.impl.portal.FileChooser.xml
- data/org.freedesktop.portal.FileChooser.xml
- src/file-chooser.c
Add a 'current_filter' element for the FileChooser response which is used to specify which filter
was selected in the file chooser.
This will allow making Gtk's 'gtk_file_chooser_get_filter' work for the portal native file chooser.
See https://gitlab.gnome.org/GNOME/gtk/-/issues/1820 for more details. I'll add a link to the corresponding gtk and xdg-desktop-portal-gtk merge/pull requests here once I have created them.
> FileChooser: Add a 'current_filter' return value

- data/org.freedesktop.impl.portal.ScreenCast.xml
- data/org.freedesktop.portal.ScreenCast.xml
- src/screen-cast.c
This is supposed to be a new addition for the clients to help them identify whether the user picked a screen or a window and what will be the content of the stream.
> Screencast: document source_type property in the response

- data/org.freedesktop.portal.FileChooser.xml
Small typo fixes for the "options" - "choices documentation.
> Fix typos in FileChooser doc

- data/org.freedesktop.impl.portal.FileChooser.xml
This reverts commit ee041ae8c8c8b0534bdd300953f131f1c93434cd.
Documentation for this parameter was already added in c616b491 so this
just duplicates it.
> Revert "Add the directory option to the file chooser impl interface"

- src/pipewire.c
destroy the registry proxy after use or else we leak it.
> pipewire: clean up the registry proxy

- src/open-uri.c
- tests/backend/appchooser.c
* open-uri: Don't crash if there is no default or latest app
g_desktop_app_info_new() requires a non-NULL argument.
Partially addresses #524.
Fixes: 69205f12 "open-uri: Show app chooser when default app does not exist"
* open-uri: Assert that find_recommended_choices yields non-NULL
choices is never NULL, but might be an array containing only NULL.
* tests: Make app chooser backend more debuggable
Instead of crashing out when our expectations are not met, return an
error that other components can log.
* open-uri: Use correct app ID to determine whether it exists
x-d-p represents apps by their app ID *without* the .desktop suffix,
but GDesktopAppInfo represents them by the app ID *with* the .desktop
suffix.
Fixes: 69205f12 "open-uri: Show app chooser when default app does not exist" …
> Fix openuri test regression (#524)

- src/open-uri.c
- src/request.c
- src/wallpaper.c
Should fix https://github.com/flatpak/xdg-desktop-portal/issues/509
> Fix wallpaper and open-uri fd leaks

- configure.ac
It seems to have been removed in https://github.com/flatpak/xdg-desktop-portal/commit/80043fc333847a3a200662d18d8f5a29fe10c5b5.
> build: drop unneeded fontconfig dependency

- src/account.c
- src/file-chooser.c
- src/open-uri.c
- src/screenshot.c
- src/xdp-utils.h
Use new XdpFd type with g_auto to make sure the file descriptor gets
closed when the function finishes.
> open-uri: Close fd after opening dir or file

- src/xdp-utils.c
- src/xdp-utils.h
- tests/Makefile.am.inc
- tests/test-xdp-utils.c
At the moment, we detect snaps by checking the AppArmor label, which works well on systems that have AppArmor loaded but fails elsewhere.  This branch attempts to fix that and also provide more information about the snap to xdg-desktop-portal.
The new strategy is as follows:
1. Perform a quick check to see whether the process is snap confined.  At present, this is checking whether the freezer cgroup membership is something snapd would place the process in.  This currently doesn't work for systems with a unified cgroup hierarchy, so will need some changes before landing.
2. If we think the process is a snap, shell out to `snap routine portal-info $pid` to identify the snap.  This will return metadata about the snap in keyfile format.  This means that the exact method of determining the …
> Don't use AppArmor to detect snap confined clients

- document-portal/document-portal.c
- src/documents.c
- src/xdp-utils.c
- src/xdp-utils.h
- tests/test-xdp-utils.c
The document portal uses different inode number when exposing a particular document in different parts of the file system.  As sandboxed apps only have a subtree of the document portal file system mounted, the "same file" checks in xdp_app_info_get_path_for_fd() would fail for document portal paths.
To fix this, we check to see whether the corresponding "by-app/$app_id" path matches the stat information of the file descriptor.
Fixes #545
> xdp-utils: check if alternate doc portal path matches in path_for_fd()

- document-portal/document-portal.c
This calls out to the `snap routine file-access` helper command, which produces output compatible with `flatpak info --file-access`.
While this command was only introduced in snapd 2.45, the failure mode with old versions is consistent with the previous behaviour: assume the snap does not have file access.
At present, the `snap routine-file-access` reports read-write or read-only access for the following:
* The snap's own data under `/var/snap` and `~/snap`.
* If the snap plugs `home`, paths under the user's home directory excluding the `~/snap` directory and top level hidden files.
* If the snap plugs `removable-media`, paths from removable media directories (`/mnt`, `/media`, and `/run/media`).
These paths should all have the same meaning inside and outside the sandbox.
> document-portal: add snap support to app_has_file_access()

- tests/Makefile.am.inc
- tests/can-use-fuse.c
- tests/can-use-fuse.h
- tests/test-doc-portal.c
* tests: Factor out check_fuse() into a file that can be shared by Flatpak
* tests: Skip FUSE tests if /etc/mtab doesn't exist
Some minimal autobuilder environments don't have the
/etc/mtab -> /proc/self/mounts symlink, so this is yet another thing
that can go wrong during build-time testing.
(This was used as a basis for flatpak/flatpak#4098)
> Factor out check_fuse() into a file that can be shared by Flatpak

- src/wallpaper.c
(/usr/libexec/xdg-desktop-portal:13660): GLib-CRITICAL **: 18:57:58.512: g_variant_get_type: assertion 'value != NULL' failed
(/usr/libexec/xdg-desktop-portal:13660): GLib-CRITICAL **: 18:57:58.512: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
(/usr/libexec/xdg-desktop-portal:13660): GLib-CRITICAL **: 18:57:58.512: g_variant_get_type_string: assertion 'value != NULL' failed
(/usr/libexec/xdg-desktop-portal:13660): GLib-ERROR **: 18:57:58.512: g_variant_new: expected GVariant of type 'a{sv}' but received value has type '(null)'
CC @mcatanzaro
> wallpaper: reflect on open-uri.c behavior, avoiding a crash

- src/settings.c
- tests/backend/Makefile.am.inc
- tests/backend/settings.c
- tests/backend/settings.h
- tests/backend/test-backends.c
- tests/portals/test.portal
With settings portal ability to load multiple backend implementations, there is a possibility that one of them will not load correctly and be placed into the list anyway. This results into failed implementation being used, we will call Read/ReadAll on it and it will fail and crash. To avoid that, we will create a temporary list, check real number of working implementations and put them into the final list we will use later.
> Settings: do not put failed implementations into the list

- src/xdp-utils.c
Flatpak 1.11.x avoids mounting anything into the app-controlled
XDG_RUNTIME_DIR, so $XDG_RUNTIME_DIR/app in the container shows up as
a symlink to /run/flatpak/app. This particularly affects apps that
set TMPDIR=$XDG_RUNTIME_DIR/app/$FLATPAK_ID and use the URI portal
to request that a file in /tmp gets opened on the host.
Manual test:
(run any Flatpak app with --command=bash)
echo "hello" > $XDG_RUNTIME_DIR/app/$FLATPAK_ID/readme.txt
xdg-open $XDG_RUNTIME_DIR/app/$FLATPAK_ID/readme.txt
Resolves: #589
Signed-off-by: Simon McVittie <smcv@collabora.com>
> utils: Remap /run/flatpak/app, for Flatpak 1.11.x

- document-portal/permission-db.c
- tests/test-permission-store.c
The permission store crashes when it attempts to remove
the last entry of an specific  table and id pair,  e.g.
"notifications", "notification", "a".
The crash occurs due to the assumption that there should
still be one entry left after the operation,  but is not
the case here.
Prevent this by writing an empty entry for this specific
table and id  pair, instead. So  that the specific  pair
is kept in the database.
I assume this is the right thing to do, due to:
1. There's a separate API for deleting table and ids pairs.
2. The removal-related code already assumes that there should
be at least one entry left after this operation.
3. It's what "flatpak permissions-reset --all" does.
Closes #573
> permission-store: Don't crash when deleting permissions

- data/org.freedesktop.impl.portal.ScreenCast.xml
- data/org.freedesktop.portal.ScreenCast.xml
- src/screen-cast.c
This is a source type that by the portal implementation backend should
be implemented as a per screen cast stream created virtual monitor. The
dimension of the stream for these types of screen cast streams are
typically determined during the pipewire stream negotiation.
---
Use case for this is e.g. gnome-network-displays like applications; anything that wants to provide a virtual monitor like functionality.
> ScreenCast: Add 'VIRTUAL' source type

- src/documents.c
- src/documents.h
- src/open-uri.c
Before this change the file manager would open inside the document portal directory like `/run/user/1000/doc/10288756` which is not very user-friendly. With this change it opens in the real filesystem path. Now actions like "Show in Files" can be properly implemented.
cc https://github.com/flatpak/xdg-desktop-portal/issues/363
> Use real filesystem path for OpenDirectory

- data/org.freedesktop.portal.FileChooser.xml
Make it explicit that patterns are case-sensitive.
Closes https://github.com/flatpak/xdg-desktop-portal/issues/225
> Clarify the docs on filters in the file chooser

- src/location.c
Currently the translation uses the geoclue enum values rather than
the documented values, which breaks consumers like geoclue's client
library that translates accuracy values according to the documentation.
> location: Update accuracy translation

- data/org.freedesktop.impl.portal.PermissionStore.xml
- document-portal/xdg-permission-store.c
- tests/test-permission-store.c
We currently have SetPermission and DeletePermission which operate
with specific apps, but we didn't have a GetPermission method that
does the same. Instead, we rely on LookUp which brings all (table,
id, app) tuples.
From what I have seen,in GNOME Control Center and what I needed
to do for Flatseal, we call LookUp, check if the app is present
among the retrieved tuples,  to then access the permission data
we are looking for (e.g, ["yes"], etc).
As more UI tools ala-flatseal appear, a GetPermission would make
more sense for such tools as these operate per-app basis.
Another reason is that the permission store data tends to grow,
which means that  LookUp  will keep bringing more and more data
unnecessarily for the case described.
Closes #583
> permission-store: Add GetPermission

- document-portal/document-portal.c
- src/email.c
- src/open-uri.c
- src/trash.c
- src/wallpaper.c
- src/xdp-utils.c
- src/xdp-utils.h
* verify_proc_self_fd: Raise a GError
This lets us log the failure reason as a debug message on failure.
* xdp_app_info_get_path_for_fd: Factor out check_same_file
As with the previous commit, this lets us log a more detailed debug
message when we don't get a match.
* utils: Add fallback definition for G_DBUS_METHOD_INVOCATION_HANDLED
When implementing GDBus methods, it's not always obvious that
"return TRUE" on error is correct - but in fact it is, because the
boolean result is handled/unhandled rather than the usual success/error.
GLib 2.68 introduced macros to make this more obvious. Backport them
here for older GLib versions.
I'm not systematically converting existing code right now, but the new
macros can be used in new code.
* email: Handle error from xdp_app_info_get_path_for_fd …
> Improve error handling when passing files by fd

- src/xdp-utils.c
In a Flatpak app, /var/config and /var/data are parallel mount points for
the same directories as $XDG_CONFIG_HOME and $XDG_DATA_HOME, which are
canonically under ~/.var/app/$FLATPAK_ID. /var/config and /var/data
don't exist as conventional FHS paths, so it seems safe to assume that
if they appear inside a Flatpak app, it's these aliases that are meant.
/var/cache and /var/tmp are not handled here, because those are
ambiguous and will need a different code structure to handle: they're
usually aliases for $XDG_CACHE_HOME and $XDG_CACHE_HOME/tmp respectively,
but it would be reasonable for a Flatpak app to have
--filesystem=/var/tmp, and not impossible for it to have
--filesystem=/var/cache/something.
Resolves: #592
> utils: Remap Flatpak /var/config, /var/data

- data/org.freedesktop.portal.Camera.xml
- data/org.freedesktop.portal.ScreenCast.xml
`pw_remote_connect_fd` does not exist any more.
Closes https://github.com/flatpak/xdg-desktop-portal/issues/617
> Update ScreenCast and Camera documentation to Pipewire 0.3 api

- src/inhibit.c
- src/remote-desktop.c
- src/screen-cast.c
The session id is defined as the object path of the session.
We should use a type of 'o' instead of 's'.
Note that the docs mentions the correct type https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-method-org-freedesktop-portal-ScreenCast.CreateSession.
> use correct type for the session object path

- src/remote-desktop.c
Uses a more meaningful error messages in case a device access wasn't provided after
starting the session
> remote-desktop: better error messages on device access failures

- src/pipewire.c
- src/pipewire.h
This ensures the portal itself can still start successfully (albeit with
reduced abilities) if PipeWire itself is non-functional.
Note that this is not just hypothetical, as I have seen various reports
of this over time.
> pipewire: Ensure roundtrips have a timeout

- document-portal/xdg-document-portal.service.in
- src/xdg-desktop-portal.service.in
Services and applications like these portals should be placed in the
session slice.
From DESKTOP_ENVIRONEMTNS[1]
> The purpose of this grouping is to assign different priorities to the
> applications. This could e.g. mean reserving memory to session
> processes, preferentially killing background tasks in out-of-memory
> situations or assigning different memory/CPU/IO priorities to ensure
> that the session runs smoothly under load.
And from man:systemd.special(7):
> session.slice
>  All essential services and applications required for the session
>  should use this slice. These are services that either cannot be
>  restarted easily or where latency issues may affect the interactivity
>  of the system and applications. This includes the display server,
>  screen readers and other services …
> Place portals in session.slice

- data/org.freedesktop.impl.portal.Settings.xml
- data/org.freedesktop.portal.Settings.xml
Specify a key for getting the system's preferred color scheme.
Fixes https://github.com/flatpak/xdg-desktop-portal/issues/629
> settings: Add color-scheme key

- configure.ac
Patch from Helmut Grohne, forwarded from a Debian bug report:
xdg-desktop-portal fails to cross build from source, because configure.ac
hard codes the build architecture pkg-config on one occasion, rather than
taking the host architecture pkg-config from $PKG_CONFIG. The relevant
occasion is unnecessary as the version check can be fused in an earlier
access of the relevant package with the right pkg-config.
[Commit message added by Simon McVittie, based on the text of the
Debian bug report.]
Resolves: https://bugs.debian.org/985411
> build: Fix cross-compilation by adjusting pkg-config use

- src/open-uri.c
Making a synchronous call into a GTK implementation of o.fd.FileManager1
can cause a deadlock, because GtkApplication makes a synchronous call
into the Inhibit portal when started in a non-GNOME, non-XFCE environment.
In this situation, each service does not take its bus name (and hence
complete service-activation) until it gets a reply from the other, which
obviously can't work.
We don't actually need a GDBusProxy here: we don't need to subscribe to
any signals, watch any properties or hold any state, so it's just as
straightforward to use g_dbus_connection_call_sync() on a just-in-time
basis.
Fixes: 69961f3f "openuri: Use FileManager1 in OpenDirectory"  
Resolves: https://github.com/flatpak/xdg-desktop-portal/issues/636
---
Not thoroughly tested yet: because the issue mentioned Thunar, …
> open-uri: Avoid calling into o.fd.FileManager1 during startup

- src/pipewire.c
- src/pipewire.h
Currently, the PipeWire registry object is destroyed when
discover_node_factory_sync finishes it's functionality. This causes
registry events to not be delivered to the global_removed_cb and
global_added_cb callbacks after discover_node_factory_sync, breaking
the functionality of the
org.freedesktop.portal.Camera.IsCameraPresent property in case of
camera device hot(un)plug.
This changes the discover_node_factory_sync function to store the
registry in the PipeWireRemote structure and destroy it in
pipewire_remote_destroy.
> Do not destroy the registry object during creation of PipeWireRemote

- .github/workflows/check.yml
- tests/Makefile.am.inc
- tests/test-doc-portal.c
- tests/test-document-fuse.py
- tests/test-permission-store.c
- tests/test-portals.c
- tests/trash.c
- tests/utils.c
- tests/utils.h
In order to run various tests, we need a working /dev/fuse, and this is
currently only possible in a privileged container [1].
Github actions workflow doesn't suppport it natively, so we need to
initialize a new one ourself, we just keep it running and execute the
commands when we need them, not to depend on a static image, so that the
github workflow can still be followed as atomic operations.
Also ensuring now that the installed tests are installed and that they're actually running.
/cc @TingPing 
[1] https://github.com/docker/for-linux/issues/321
> CI: Use a privileged docker container to support FUSE tests

- src/portal-impl.c
this fixes an possible issue in  `org.freedesktop.portal.Settings` that they would call an fallback backend first instead of the supported one,  possibly breaking the `org.freedesktop.appearance.color-scheme` support, if both implements it.
> Sort implementations based on the `UseIn` key

- src/xdp-utils.c
Flatpak now puts the document portal into `/run/flatpak/doc`, which does not exist on the host, so we need to remap it. Looks like https://github.com/flatpak/xdg-desktop-portal/commit/6692c874c97906ed12d219dfa26f977eb01f47f4 forgot about it.
Fixes #671, tested with my app.
> xdp-utils: Remap /run/flatpak/doc to host

- src/session.c
We don't seem to close our XdpSession when XdpImplSession::Closed() signal is called and we don't emit XdpSession::Closed() signal when it actually happens. Better description is in each commit.
> Make sure to properly close sessions when invoked from portal backend implementation

- .github/workflows/docs.yml
The job works properly once installed, see https://github.com/bilelmoussaoui/xdg-desktop-portal/runs/4499618040?check_suite_focus=true
and can be checked at https://bilelmoussaoui.github.io/xdg-desktop-portal/
> CI: install ca-certificates for docs job

- src/pipewire.c
- src/pipewire.h
This reverts commit fbe26534e14c48481d578da6908d47a53915b77b.
The commit introduced a crash.
> Revert "pipewire: Destroy registry object with remote"

- doc/docbook.css
It makes the page easier to read.
This is how it looks like on a 1080p display:
> Add max-width

- .github/workflows/check.yml
- .github/workflows/docs.yml
- configure.ac
- document-portal/Makefile.am.inc
- src/Makefile.am.inc
- src/sd-escape.c
- src/sd-escape.h
- src/xdp-utils.c
- src/xdp-utils.h
- tests/Makefile.am.inc
- tests/test-xdp-utils.c
This is a rework of #581 and dependent on #718, but I'm marking it as a draft because sadly it doesn't work for the one case I actually need it: GNOME Software.
In the case of, say, non-Flatpak Epiphany, the app ID can be successfully gleaned from the systemd unit which looks like `app-gnome-org.gnome.Epiphany-182352.scope`. But in the case of gnome-software (which runs as `/usr/bin/gnome-software --gapplication-service`) the unit looks like `app-gnome-gnome\x2dsoftware\x2dservice-9502.scope` (where 9502 is the pid in my case) so parsing that in any way is not going to get us the correct app ID of `org.gnome.Software`. So I think we need to look for a better way to get app IDs...
> Get app ID via libsystemd for unsandboxed apps

- data/org.freedesktop.portal.Background.xml
- data/org.freedesktop.portal.Camera.xml
- data/org.freedesktop.portal.Documents.xml
- data/org.freedesktop.portal.FileTransfer.xml
- data/org.freedesktop.portal.GameMode.xml
- data/org.freedesktop.portal.Inhibit.xml
- data/org.freedesktop.portal.Location.xml
- data/org.freedesktop.portal.Notification.xml
- data/org.freedesktop.portal.RemoteDesktop.xml
- data/org.freedesktop.portal.ScreenCast.xml
- data/org.freedesktop.portal.Secret.xml
- data/org.freedesktop.portal.Session.xml
- data/org.freedesktop.portal.Wallpaper.xml
Fix the various links to portals, methods and signals, with the
resulting re-formatting required.
Fix some of the arguments that previously spanned over two lines, this
results in incorrect rendering.
Fix the Wallpaper value lists to use a proper variablelist like the
other portals.
And smuggle in a typo fix or two and some whitespace fixes vim decided
to apply.
> doc: fix links and some formatting in the portal.* interfaces

- src/xdp-utils.c
See commits. The warnings were a bit annoying.
CC @jhenstridge since this is touching Snap code
> Small cleanups on xdg-utils.c

- Makefile.am
- Makefile.am.inc
- configure.ac
- data/org.freedesktop.impl.portal.DynamicLauncher.xml
- data/org.freedesktop.portal.DynamicLauncher.xml
- src/Makefile.am.inc
- src/background.c
- src/dynamic-launcher.c
- src/dynamic-launcher.h
- src/notification.c
- src/request.c
- src/validate-icon.c
- src/xdg-desktop-portal.c
- src/xdg-desktop-portal.service.in
- src/xdp-utils.c
- src/xdp-utils.h
This is not ready to be merged since I haven't implemented the gnome backend or the libportal side of it, and I haven't tested it. But it can be reviewed.
For context see #681 and #326
> Add dynamic launcher portal

- src/screen-cast.c
Otherwise I get the following error message:
> Received restore data in invalid variant format ('(suv)'; expected '(suv)')
> screencast: Analyze the value we get straight away

- src/Makefile.am.inc
- src/xdp-utils.c
sd-escape.c and sd-escape.h were skipped when building without systemd,
but they contain functions needed for xdg-desktop-portal to build.
Fortunately, neither file actually requires anything specific to systemd
so they can just always be included as part of the sources.
> fix building without systemd

- data/org.freedesktop.portal.DynamicLauncher.xml
Currently the word 'desktop' is considered a single-word paragraph, and
the short description is truncated in the TOC.
> DynamicLauncher: fit short_description on one line

- po/id.po
This PR updates the Indonesian translation by fixing a couple of grammatical errors and changing some words to better fit the context*.
*) While `nyalakan` is indeed a correct substitute for `turn on` in English, it implies ignition as a part of the process, whereas nothing is (hopefully) being ignited as components like the speakers are being turned on. Therefore, `hidupkan` (lit. `to put alive`) is most likely a better fit.
> l10n: update Indonesian translation

- data/org.freedesktop.portal.DynamicLauncher.xml
Launchers are installed into the desktop environment's menu, not to the
desktop.
Fixes #755
> DynamicLauncher: Clarify confusing short description

- src/xdp-utils.c
Since #696, the arguments sent to background portal implementations
contained the app-id in quoted form. Implementations, in turn, created
invalid autostart files.
> background-portal: Stop sending app-id quoted

- README.md
The current Link points to the GitHub Mirror, not the original Repo
> Fix Link to xdg-desktop-portal-kde

- src/xdp-utils.c
On success lookup_ns_from_pid_fd() is meant to return 0, which is what
FALSE is also defined as.  Therefore, this typo could lead to
surprises in case of a programmer error.
> utils: Fix typo

- src/xdp-utils.c
Fallout from b19eed79d8f685138ac788d1b158b9e58f9ad4f7
> utils: Remove unused macro definition

- tests/__init__.py
- tests/meson.build
- tests/templates/__init__.py
- tests/templates/email.py
- tests/test_email.py
- tests/test_trash.py
For complex portals like the InputCapture portal, the current test suite
is difficult to use and adapt. A much simpler approach is to use
dbusmock to provide the impl.portal emulation, use Python to poke at the
actual DBus API of the portal and have xdg-desktop-portal sit in
between to negotiate the two.
This patch adds a test suite that provides enough infrastructure to add
tests for other portals in a similar manner - luckily the impl side is
relatively trivial to implement in dbusmock.
Currently implemented are the equivalents to the tests/email.c and
tests/trash.c tests. The email tests is missing the test for parallel
ComposeEmail calls though.
Easiest invoked via pytest, one of XDP_UNINSTALLED or LIBEXECDIR must be
set to run from the git tree or using the installed …
> Add a dbusmock-based Python test suite

- .github/workflows/check.yml
The github syntax for matrix.include requires it to be a single value,
not an array. The result of this was that the value wasn't "thread" but
rather "Array" and never triggered the condition we had for it.
> CI: actually run the thread sanitizer jobs

- .github/workflows/check.yml
- document-portal/Makefile.am.inc
- document-portal/document-portal.c
- document-portal/permission-store.c
- src/glib-backports.h
- src/meson.build
- tests/backend/test-backends.c
- tests/test-doc-portal.c
- tests/test-permission-store.c
- tests/test-portals.c
Duplicate of the existing autotools run, just using meson instead for build/test/install. However - meson has its own TAP parser which is unhappy with the `G_MESSAGES_DEBUG='all'` output that floods stdout (see also d661854d4c6298976f61438cc6d9bbc1ac9a967f). Adding `g_log_writer_default_set_use_stderr(TRUE)` fixes that and that's probably fine for anything in `tests/`, but I also had to add this to the document portal and the permission store (afaict they're dbus-activated) where it's not fine. 
Any hints on how to convince glib to spew debug to stderr instead would be appreciated, there must be something obvious I'm missing here.
> Add a CI run for the meson build

- src/realtime.c
The RTKit argument for the priority in MakeThreadHighPriority is
supposed to be an int, not a uint.
This avoids errors like: Jul 19 11:16:34 wtay rtkit-daemon[1474]:
Failed to parse MakeThreadHighPriority() method call: Argument 2 is
specified to be of type "int32", but is actually of type "uint32"
> realtime: fix priority type in MakeThreadHighPriority

- data/org.freedesktop.portal.Realtime.xml
The types for the properties MaxRealtimePriority and RTTimeUSecMax are incorrect in the D-Bus xml interface file: MaxRealtimePriority should be type 'i' (int32) and RTTimeUSecMax should be type 'x' (int64).  This changes them to match the types used in the realtime.c source file as well as matching the types used by rtkit for these properties.
> realtime: Fix property types

- src/realtime.c
- src/xdp-utils.c
- src/xdp-utils.h
Closes #837 
This is tested from inside flatpak, using freedesktop-sdk 22.08beta, with a Pipewire patch: https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/1332#note_1481517
Also a rebuilt version of the Ardour flatpak.
__Update__: this reworked version works fine. Ignore what follows.
__Update2__: Refactored the code a bit more.
~~Two things about this PR:~~
~~- I now get permission error instead of not found error, and Bustle no long shows  the call to `org.freedesktop.RealtimeKit1.MakeThreadRealtimeWithPID` on the system bus.~~
Before (system-bus):
note the thread id isn't consistent.
The error:
After (session-bus):
~~The pid and thread id are consistent with inside the sandbox. The PID in the error is the one of `xdg-dbus-proxy`~~
~~- I am not sure is the way to remap …
> Issue #837 - Remap thread ids

- src/realtime.c
- src/xdp-utils.c
- src/xdp-utils.h
- This was a left over from a 1.12 -> main port
(sorry about that and I missed it at the review - caught it backporting)
> Issue #837 - Fix function name

- src/realtime.c
- src/xdp-utils.c
- src/xdp-utils.h
Backport to 1.12.
So that maybe it can make it to Fedora 36.
> Issue #837 - Remap thread ids - backport to 1.12

- data/org.freedesktop.portal.Location.xml
> Fix documentation on location keys returned - these are capitalized.

- src/account.c
- src/documents.c
- src/documents.h
- src/file-chooser.c
- src/open-uri.c
- src/screenshot.c
In some context where the screenshot could contain sensitive information
like a QR code, it would make sense to allow the application that scans
the resulting screenshot to remove it just after it is done with it.
Use case: https://gitlab.gnome.org/World/Authenticator/-/issues/280
> Screenshot: Allow deleting the file

- data/org.freedesktop.impl.portal.Screenshot.xml
- src/screenshot.c
- src/screenshot.h
- src/wallpaper.c
- src/xdg-desktop-portal.c
- tests/screenshot.c
This PR implements a new permission table and value for screenshots, which allows portal implementations to skip the sharing dialog.
Closes https://github.com/flatpak/xdg-desktop-portal/issues/649
> Screenshot permission, attempt 2

- document-portal/xdg-document-portal.service.in
- document-portal/xdg-permission-store.service.in
Follow-up to https://github.com/flatpak/xdg-desktop-portal/pull/614
I think `xdg-permission-store` fits the description from `man:system.special(7)`
>background.slice
> All services running low-priority background tasks should use this slice. This permits resources to be preferentially assigned to the other slices. Examples include non-interactive tasks like file indexing or backup operations where latency is not important.
> Move xdg-permission-store to Background slice

- .github/workflows/check.yml
- .github/workflows/docs.yml
- doc/meson.build
It's the fuuuuture! Also, meson has better autodetection of features, so we don't need to install *all* dependencies just to build the docs.
> CI: build the docs with meson

- tests/__init__.py
- tests/portals/test.portal
- tests/templates/__init__.py
- tests/templates/remotedesktop.py
- tests/test-document-fuse.py
- tests/test_remotedesktop.py
This sits on top of #863 
Add support for session in the python portal tests and a minimal RemoteDesktop test case that creates a session and verifies that it was closed in the impl as well. And then the same the other way with the `Closed` signal bubbling up.
Motivated by #508, verifies that bug isn't actually x-d-p's fault anymore.
> Add tests for Session.Close() and Session.Closed

- data/org.freedesktop.portal.Camera.xml
Add a description of what AccessCamera() is doing.
Note that there are currently no supported options in OpenPipeWireRemote().
> doc: Update camera documentation.

- src/screenshot.c
- tests/backend/screenshot.c
Right now, we always assume screenshot portal implementations provide a
`PickColor()` implementation, which is not necessarily true.
This commit adds a `version` property to the impl that we can use to
propagate for our own D-Bus interface. That way, clients can properly
check whether the PickColor API is available.
Fixes https://github.com/flatpak/xdg-desktop-portal/issues/686 for me
> screenshot: Add Impl:version property and query it

- tests/meson.build
This mirrors what the Meson build does for build-time tests, letting test frameworks like ginsttest-runner and autopkgtest see which parts were successful and which parts failed as individual tests.
> meson: In installed-tests, invoke test-portals once per portal

- tests/meson.build
- tests/test-portals.c
We have some very basic test coverage even if libportal isn't used, and that needs setup_dbus_daemon_wrapper().
---
The Debian 11 backport mentioned in #893 needs this: we don't have libportal in Debian 11 (it will be in Debian 12), but I still want to enable whatever test coverage remains.
> Fix Meson build when tests are enabled but libportal is disabled

- src/glib-backports.h
- tests/backend/test-backends.c
- tests/meson.build
- tests/test-doc-portal.c
- tests/test-permission-store.c
- tests/test-portals.c
For the benefit of Flatpak apps that need recent portal features, it's useful for newer xdg-desktop-portal releases to be backportable to LTS distributions like Debian stable, Ubuntu LTS and RHEL (in Debian, I maintain an official backport of the versions we aim to have in Debian 12, backported for Debian 11 users).
* tests: Don't apply Meson's strict TAP parsing for older GLib
In older GLib, we don't have a straightforward way to avoid debug
messages going to stdout, which would be tolerated by Autotools' TAP
parser but not by Meson's stricter TAP parser.
* tests: Include src/glib-backports.h where needed
The tests call g_log_writer_default_set_use_stderr(), but that function
isn't available in older GLib.
We have to include this as src/glib-backports.h, because
tests/glib-backports.h …
> Fix Meson build of 1.15.x on Debian 11 (GLib 2.66)

- data/org.freedesktop.portal.GlobalShortcuts.xml
- data/org.freedesktop.portal.Request.xml
This way we don't need to copy them over to use them.
> Fix Qt type annotation for some portals

- data/org.freedesktop.impl.portal.GlobalShortcuts.xml
- data/org.freedesktop.portal.GlobalShortcuts.xml
- src/global-shortcuts.c
- src/request.c
We were always returning 2, which is not correct.
> global-shortcuts: Responses should succeed if nothing wrong happened

- data/org.freedesktop.impl.portal.GlobalShortcuts.xml
- data/org.freedesktop.portal.GlobalShortcuts.xml
I'm a bit surprised that the different tooling didn't complain about this, is this something that should be supported?
> global-shortcuts: Signal arguments are outputs

- .github/workflows/check.yml
- .github/workflows/docs.yml
Node 12 is deprecated so let's bump the actions to newer versions that use Node 16. See
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> CI: bump some actions to newer versions

- .github/workflows/check.yml
This sits on top of #925 
Instead of two near-identical workflow jobs, push the buildsystem into the matrix and make the various `run:` commands dependent on that matrix value. This removes *some* duplication, albeit not that much. But it's probably better than having this separately.
In particular, I'm interested in the `CI: only pass the sanitize CFLAGS through for autotools` commit because that is what makes building libei from git harder in #714.
> CI: make the autotools vs meson decision a matrix field

- src/file-chooser.c
Previously this was evaluating as if (gvariant != NULL) which is always true if the option is present, this caused all files to be passed down as read-write regardless of what the impl, app and user requested.
I tested this change locally using Bustle and one can see that the permission store gets 
```
([handle 0], uint32 7, 'com.belmoussaoui.ashpd.demo', ['read', 'grant-permissions'])
```
rather than 
```
([handle 0], uint32 7, 'com.belmoussaoui.ashpd.demo', ['read', 'write', 'grant-permissions'])
```
when the user ticks the "read-only" choice in the file picker.
> file-chooser: Set writable flag correctly

- tests/meson.build
* tests: List lists of sources one per line in alphabetical order
This will make it easier to add more without merge conflicts or a very
long line.
* tests: Add missing dependency on permission-store GDBus header
When doing a clean build of x-d-p, we need generated headers to have
been generated before we try to compile code that includes them.
Resolves: https://github.com/flatpak/xdg-desktop-portal/issues/942
> tests: Add missing dependency on permission-store GDBus header

- document-portal/file-transfer.c
Apps might send us a D-Bus message without attached fds. We need to handle that without criticals.
> file-transfer: Handle bad requests

- src/xdp-utils.c
- tests/test-xdp-utils.c
There is no restriction to reverse DNS App IDs in the systemd spec and we don't rely on it either.
> utils: Match all valid App IDs from systemd unit names

- SECURITY.md
Now that 1.16 is out, we can drop 1.12 from the list of supported versions.
> docs: Update supported versions table

- meson.build
- src/dynamic-launcher.c
- src/dynamic-launcher.h
- src/glib-backports.c
- src/glib-backports.h
- src/rewrite-launchers.c
- src/xdg-desktop-portal.c
- src/xdp-utils.c
GLib 2.66 was released in September 2020.
Note: this pull request depends on #977.
> Drop pre-2.66 GLib compatibility layer

- document-portal/gvdb/gvdb-builder.c
GLib 2.76 added a compiler annotation to ensure that the value returned by g_string_free() is used, as it catches potential leaks.
There is a false positive in the GVDB code, but since the C compiler cannot distinguish it from an actual positive case, let's re-arrange the code a bit to avoid a compiler warning.
Since the order of evaluation of arguments is undefined in C, we also need to extract the string length before freeing GString, to avoid possible side effects of g_string_free().
> Avoid compiler warning with recent GLib versions

- src/documents.c
- src/documents.h
- src/file-chooser.c
When we are given a current_file that is in the document store,
translate it back to its host location, so we don't present the
user with an unseemly and confusing path in the UI.
This works well for existing files, but the GTK file chooser does
not preserve the filename if the file does not exist.
Helps with: https://github.com/flatpak/xdg-desktop-portal/issues/982
> Improve the filechooser behavior

- src/portal-impl.c
- src/portal-impl.h
- src/xdg-desktop-portal.c
If no portal backend for a given interface is found, a fallback is always tried anyway, despite that fallback not being listed as compatible with the current desktop environment.
Sometimes it's good that a fallback is returned; e.g. the xdg-desktop-portal-gtk file chooser backend is technically usable anywhere, however, some backends might be specifically designed to only work in a specific desktop environment, e.g. xdg-desktop-portal-gnome.
In order to avoid creating portals with non-functional backends, make sure it's possible to create a proxy object for the interface and D-Bus name, and that it launched successfully (i.e. has no name owner after creating the proxy).
----
Opening this against xdg-desktop-portals-1.16 because hopefully …
> portal-impl: Only return found implementation if it launched

- src/documents.c
Unused since 60e7984fce78f2bb2baf62ae9d9400976f44a74c
> Fix a unused variable compiler warning

- data/org.freedesktop.impl.portal.Print.xml
- data/org.freedesktop.portal.Print.xml
- src/print.c
It makes sense to allow changing the button label, in particular for the PreparePrint call. We allow
the same for file chooser dialogs.
> print: Add an accept_label option

- tests/__init__.py
- tests/meson.build
- tests/templates/meson.build
After successfully paging everything out about this test suite, I struggled to run it - because the defaults only work on autotools but not on meson. This patchset fixes (and documents) this a bit better. Once #977 is merged we can probably drop a few of these.
> A few fixes for the pytest test suite

- CONTRIBUTING.md
- RELEASE_HOWTO.md
As of meson 0.55 this is the backend-agnostic compiler command so let's use it to standardize across projects. We require 0.56 anyway.
> Switch from ninja to meson compile in the docs

- src/file-chooser.c
Addressing issue https://github.com/flatpak/xdg-desktop-portal/issues/982
> Use the host path when current_folder points to the document storage 

- doc/portals-conf.rst
As described above in the page the group name is [preferred]
> Fix configuration group name in documentation

- .github/workflows/check.yml
- meson.build
- meson_options.txt
- tests/meson.build
Previously the pytests were enabled if pytest and the required python modules were available. Make this more explicit by having a meson feature for that.
Suggested by @smcv in https://github.com/flatpak/xdg-desktop-portal/pull/1016#issuecomment-1542305566
> meson: expose the pytest suite as meson feature and require it in the CI

- src/open-uri.c
Opening the file by calling `org.freedesktop.portal.OpenURI` `OpenFile` method launches the target application with the `/run/user/...` path. This can confuse user to show the strange file location. In case of Libreoffice it opens the file as read only (despite it's not read only).
Resolves: #1011
> Translate sandboxed path to host path on OpenFile

- src/screenshot.c
- src/wallpaper.c
If for some reason, the permissions dialog cannot be shown, there is no response sent to the caller, so it may remain waiting forever.
This PR ensures that there is always a response sent, even when the dialog has not been shown.
The response is similar to the "No permissions" response (value = 2), as  the caller will not have permission to continue.
The same issue happens in both, Screenshot and Wallpaper.
> Always send response even if permissions dialog cannot be shown

- README.md
Cinnamon recently resolved a request [1]  to have a portal backend for their DE by introducing xdg-desktop-portal-xapp. So let's add that to the list of known portal backendss
[1]: https://github.com/linuxmint/cinnamon-desktop/issues/202
[2]: https://github.com/linuxmint/xdg-desktop-portal-xapp
> README: add Cinnamon portal

- data/org.freedesktop.impl.portal.FileChooser.xml
- data/org.freedesktop.portal.FileChooser.xml
- src/file-chooser.c
Closes https://github.com/flatpak/xdg-desktop-portal/issues/796
Supercedes: https://github.com/flatpak/xdg-desktop-portal/pull/874
> Support current_folder with FileChooser.OpenFile

- data/org.freedesktop.impl.portal.RemoteDesktop.xml
- data/org.freedesktop.portal.RemoteDesktop.xml
- src/remote-desktop.c
- src/xdg-desktop-portal.c
- tests/meson.build
- tests/templates/remotedesktop.py
- tests/test_remotedesktop.py
This is intended as replacement for the `NotifyFoo` methods. libei
provides a more flexible and powerful method of sending input events to
the compositor.
A new method `ConnectToEIS` requests a file descriptor from the compositor
which can then be plugged into libei.
Once established, the communication between compositor and application
is direct, without the need to go through the portal process(es).
To avoid ambiguities between NotifyFoo and input events sent via libei,
any application that uses an EIS connection cannot use the NotifyFoo
methods.
One notable comment: I decided to pass the EIS connection down through the `impl.portal` instead of pipewire's approach of having the portal connect directly. Unlike the single pipewire daemon, an EIS implementation can be provided by multiple …
> remote-desktop: add the ability to communicate via an EIS socket

- data/org.freedesktop.impl.portal.RemoteDesktop.xml
- data/org.freedesktop.impl.portal.ScreenCast.xml
- data/org.freedesktop.portal.RemoteDesktop.xml
- data/org.freedesktop.portal.ScreenCast.xml
- src/meson.build
- src/remote-desktop.c
- src/restore-token.c
- src/restore-token.h
- src/screen-cast.c
- src/session.c
- src/session.h
- src/xdg-desktop-portal.c
- src/xdp-utils.c
- src/xdp-utils.h
This adds persistent remote desktop sessions similar to persistent
screen cast sessions. What it means is that applications can ask for
sessions to be "saved" either temporarily in the portal, or in the
permission store, and later be restored at will, without any interactive
dialog showing up.
It works the same way, by the Start() method returning a restore token,
and similarly to the screen cast variant, passing the same restore token
to the SelectDevices() method the next time.
Closes: https://github.com/flatpak/xdg-desktop-portal/issues/850
-----
Also contains a bunch of cleanups to the screen cast and remote desktop portal specification.
> Persistent remote desktop sessions

- meson.build
- meson_options.txt
- src/meson.build
- src/xdg-desktop-portal.c
- tests/camera.c
- tests/test-portals.c
PipeWire has solidified its position in the Linux world over the last few years, and nowadays pretty much all relevant Linux distributions ship PipeWire 0.3.
Make the PipeWire dependency required.
> Make PipeWire dependency mandatory

- tests/meson.build
- tests/templates/meson.build
They were there, but they didn't run as part of `meson test`.
Cc: @maxhbooth
> tests: Hook up clipboard tests

- src/global-shortcuts.c
Currently the Global Shortcuts portal emits the 3 signals of the D-Bus interface (Activated, Deactivated, and the ShortcutsChanged signals) using the auto-generated D-Bus functions (xdp_dbus_global_shortcuts_emit_*).
These functions end up calling their GObject signals, which call into the signal handlers, which then finally call g_dbus_connection_emit_signal().
The problem is that they call g_dbus_connection_emit_signal() passing NULL to the 'destination_bus_name' parameters, which GDBus documents it to "emit to all listeners". That means we are actively sending these shortcut events to all applications that are willing to listen to these signals!
Fix that by calling g_dbus_connection_emit_signal() directly, and passing the sender bus name properly. This is the same approach that the …
> global-shortcuts: Limit signals broadcast to sender

- .github/workflows/check.yml
- tests/meson.build
All our tests must be invocable in parallel, so let's make use of that. This brings the pytest run down to around 8 seconds on my machine.
Unfortunately the -n auto command is available only if xdist is available too and pytest fails if we provide it otherwise so we need to check if we have that module.
This reduces the need for #1057
> tests: run pytest with -n auto if pytest-xdist is available

- tests/__init__.py
- tests/conftest.py
- tests/meson.build
- tests/templates/globalshortcuts.py
- tests/templates/remotedesktop.py
- tests/test-document-fuse.py
- tests/test_clipboard.py
- tests/test_email.py
- tests/test_globalshortcuts.py
- tests/test_remotedesktop.py
- tests/test_trash.py
A few cleanups to the test suite, the meat is in the last patch though which changes our dbusmock use-case from subclassing (and thus using the unittest approach) to a manually handled fixture. This means we can use all of pytest' features, now, including things like `pytest.mark.parametrize()`.
We no longer need the test classes now but they provide a convenient namespacing.
Note that #714 needs updates if this one gets merged, or vice versa.
> Use dbusmock via a pytest fixture

- README.md
This should make it more clear that only portal APIs from 1.{2,4,...} should be used in production.
> readme: Claify versioning scheme

- tests/meson.build
Some of our typing annotations use features from 3.9 - that version is now almost 3 years old which should be enough for an in-tree test suite.
Fixes #1067
---
quickfix, we can probably clean up a few things after this but that'll have to wait until I'm back.
> tests: Check for python3.9

- src/open-uri.c
Fixes #876
I've also notices a typo in handle_open_directory, apparently because it was copied from handle_open_file...
> open-uri: Pass activation token to the FileManager1 interface

- data/org.freedesktop.portal.Settings.xml
- src/settings.c
The backend returns a variant, and this was mistakenly being put inside another
variant when returned to the original caller.
Fixes https://github.com/flatpak/xdg-desktop-portal/issues/789
> settings: Fix values from read being variants inside variants.

- document-portal/document-portal-fuse.c
The recent Clang compiler (LLVM 16) became stricter so compiling this code on 32 bit arch results in a error.
Relevant log: https://pkg-status.freebsd.org/beefy17/data/main-i386-default/p4785b313b958_se8efee297c/logs/xdg-desktop-portal-1.16.0_1.log
> document-portal: Use correct signature for xdp_fuse_forget

- doc/meson.build
- meson.build
- meson_options.txt
Downstream distributions will want to build and package man pages, but generally won't need to build the docbook themselves.
> Allow building man pages without docbook

- src/portal-impl.c
The settings portal is discovered using find_all_portal_implementations, which looked for any portal that provided the implementation, regardless of configuration or UseIn=.
The new portal configuration allows us to specify which portals should be considered for each interface. Update find_all_portal_implementations to respect the configuration.
Fixes: https://github.com/flatpak/xdg-desktop-portal/issues/1017
> Respect portal configuration for find_all_portal

- doc/portals-conf.rst
- src/portal-impl.c
Previously, we would search for a user-specific portals.conf as highest precedence, and then iterate through desktop environments, searching for a user-specific desktop-specific file followed by a system-wide desktop-specific file. Now, the precedence order is consistently that directories are most important, we only pay attention to desktop environments within a single directory, and desktop-specific configuration is always higher-precedence than generic within the same directory.
Previously, desktop environments and OS vendors had to install their per-desktop configuration into /etc, contradicting the general design principle of putting defaults in /usr and reserving /etc for sysadmin overrides. Now, we search both /etc and /usr/share (with typical environment variables and build-time …
> Make the search order for portals.conf consistent with mimeapps.list

- data/org.freedesktop.portal.InputCapture.xml
Currently the documentation mentions the need of passing a handle token but it is not used as the method itself doesn't return an object path.
The Disable/Release methods don't take such option, so I assumed it is a copy/paste failure
cc @whot
> docs: Clarify InputCapture.Enable options

- src/location.c
- src/screenshot.c
- src/wallpaper.c
Applications which are not flatpaks don't enforce that the app id has a
matching desktop file and in this case info is NULL and we crash. Fall
back to the app ap when we can't get the name from the desktop file.
Same issue in screenshot, wallpaper and location.
Also changing the code to be more similar.
> Handle app_id's not havinge a matching .desktop file

- data/org.freedesktop.impl.portal.Settings.xml
- data/org.freedesktop.portal.Settings.xml
Accent colors provide a way for users to personalize their desktop in a simple, developer-friendly, and effective way. Throughout the community there has been a general interest in the inclusion of accent colors within apps and desktop environments. This proposal aims to standardize an accent color key on the Settings portal.
A new key on the Settings portal, `accent-color`, would be defined under the `org.freedesktop.appearance` namespace. The value of this key is a variant. In the case that an accent color is requested, the underlying value would be a struct containing three doubles, each being an RGB value in the range of [0,1]. Whereas, if the user has no preference or wants the application to use their own branding colors, the type will be a uint32 with the value 0, representing no …
> Accent color on settings portal

- data/org.freedesktop.impl.portal.ScreenCast.xml
- data/org.freedesktop.portal.RemoteDesktop.xml
- data/org.freedesktop.portal.ScreenCast.xml
- src/screen-cast.c
From the commit that introduces it:
This uuid is intended to be used for matching a PipeWire stream with a
libei region, so that one e.g. can emit absolute pointer events using
libei on a window screen cast. This was not possible before, since there
was no way to match a region with a stream. This also makes it easier to
pair streams and libei regions in general, as one doesn't need to look
at any sizes or positions.
See https://gitlab.freedesktop.org/libinput/libei/-/merge_requests/246.
Cc: @whot
> Add mapping_id to streams

- data/org.freedesktop.portal.Email.xml
- src/email.c
- tests/email.c
- tests/email.h
- tests/test-portals.c
- tests/test_email.py
If we validate email addresses, at least do it by following some existing specification and document it.
It remains on app developers to:
* make sure addresses are ASCII-only, by converting international labels to Punycode
* remove anything but the addresses, `Some Name <name@example.com>` is not accepted
Fixes #944 (closed in a hurry by @matthiasclasen but @smcv agreed there was a bug to solve)
> email: validate addresses following the HTML specs

- src/background.c
Print a more helpful message, and don't hide it behind a debug flag.
Closes: https://github.com/flatpak/xdg-desktop-portal/issues/1104
Closes: https://github.com/flatpak/xdg-desktop-portal/issues/1009
> background: Communicate killing apps better

- src/xdp-utils.c
`xdp_app_info_rewrite_commandline` has to respect `quote_escape` also when no commandline is given.
> xdg-utils: Properly quote flatpak command

- data/org.freedesktop.impl.portal.ScreenCast.xml
The same documentation exists for the corresponding frontend function. No functional changes.
Closes: https://github.com/flatpak/xdg-desktop-portal/issues/468
> screencast/impl: Document 'cursor_mode' property

- src/restore-token.c
- src/restore-token.h
- src/session.c
- src/session.h
- src/xdg-desktop-portal.c
Not when the session is closed. See patches.
Closes: https://github.com/flatpak/xdg-desktop-portal/issues/1124
> Delete transient permissions when peer dies

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
A request from @GeorgesStavracas that I accepted to do.
It makes the user choose between:
- Creating an issue for a bug report
- View the security policy (since a SECURITY.md is in place)
- The XDG Desktop Portals Matrix room for help/support
Note: My fork is set with this PR branch as default, so you can check the result on it
> Setup the issue template chooser

- src/session.c
See also 2f73d190fd for a longer explanation. In particular, this is required for libportal to receive the signals as that library does not AddMatch for the signals but expects them to be received.
cc and with thanks to @jadahl
> session: Limit the Session.Closed signal to the sender

- data/org.freedesktop.portal.RemoteDesktop.xml
- src/request.c
One is just a documentation issue, the second one *should*'ve produced warnings on every use of  `Camera.OpenPipeWireRemote` so I'm a bit worried why this hasn't shown up anywhere.
> Fix two issues with the spelling of PipeWire

- RELEASE_HOWTO.md
- SECURITY.md
I forgot to do that when releaseing 1.18. Do it now, and document it so neither I nor anyone else forgets about it in the future.
> Update SECURITY.md and document it

- meson.build
- meson_options.txt
the old automake scripts would allow for building without flatpak, as the xml file would just not be copied (because it doesn't exist) so it wouldn't be used to generate files.
this allows similar behaviour by not requiring the flatpak dependency in meson.
fix for #1099
> meson.build: allow linux to build without flatpak installed

- document-portal/document-portal-fuse.c
This will make sure the pointer isn't used improperly.
> document-portal-fuse: reduce the scope of a pointer

- meson.build
This fixes WARNING: Project specifies a minimum meson_version '>= 0.56.2' but uses features which were added in newer versions:
* 0.58.0: {'str.replace'}
> meson.build: Increase meson version

- doc/meson.build
- doc/portals.conf.rst.in
Generate a synopsis, and tag it a bit more.
Closes: https://github.com/flatpak/xdg-desktop-portal/issues/1096
> docs: Rework portals.conf manpage

- document-portal/file-transfer.c
- This fixes "GTask finalized without ever returning (using g_task_return_*()). This potentially indicates a bug in the program." errors.
> file-transfer: return a value from task

- data/org.freedesktop.portal.InputCapture.xml
A barrier is either at the top or at the left edge, not both. This means the actual barriers need to go from zone->x to zone->width - 1, the next pixel (zone->x + zone->width) is the first pixel of the adjacent zone if any.
We could allow this in the spec but it makes implementations a lot harder: on a two-screen setup the edge pixel would need special casing, the barrier 0-1920 and 1920-3840 are both valid on either screen despite having a single-pixel overlap. An easier approach is to make sure each barrier only covers the pixels intended, i.e. 0-1919 and 1920 to 3839 in this case.
cc @jadahl
> doc: Fix the InputCapture barrier examples

- CONTRIBUTING.md
Add a caveat on portal file locations to CONTRIBUTING.md as Meson's defaults will cause xdg-desktop-portal to look for portal files in locations that are not used by distributions like Arch and Fedora.
> docs: Add caveat on portal config file locations

- src/realtime.c
- src/xdp-utils.c
Mapping pids/tids is only necessary when apps are running inside another pid namespace. Apps on the host usually do not. If they put parts of themselves into one, it's their responsibility to do the mapping.
Instead of having to make sure that the app is not a host app before calling this function, handle host apps trivially by not mapping anything and returning success.
---
This change should only affect the gamemode portal when called from a host app.
> utils: Handle host apps in app_info_map_pids

- data/org.freedesktop.impl.portal.GlobalShortcuts.xml
- data/org.freedesktop.portal.GlobalShortcuts.xml
On X11 and wayland timestamps are using the monotonic clock for input events, global shortcuts tie in closely with this. This patch brings it in line using the same wording as wayland events.
This is technically a breakage in the spec, but pragmatically brings it in line with the current real world implementations.
Fixes #1054
> global-shortcuts: Convert timestamp to

- data/org.freedesktop.portal.Documents.xml
- src/gamemode.c
- src/generate-method-info.py
- src/memory-monitor.c
- src/meson.build
- src/network-monitor.c
- src/notification.c
- src/proxy-resolver.c
- src/realtime.c
- src/request.c
- src/sd-escape.c
- src/trash.c
- src/xdg-desktop-portal.c
- src/xdp-method-info.c
- src/xdp-method-info.h
- tests/meson.build
- tests/test-xdp-method-info.c
One of the more frustrating things to debug when adding interfaces was for me to hunt down where I needed to special-case a portal method so it initializes correctly, specifically `method_needs_request` and `get_token`.
Both can be automated with a generated file, though that requires a bit of cleanup first because some portals were using the fallthrough behaviour (making both of those functions more unpredictable than they need to be).
> Automate method_needs_request() and token lookup

- data/org.freedesktop.impl.portal.Access.xml
Closes: https://github.com/flatpak/xdg-desktop-portal/issues/1041
> Document the return value of AccessDialog()

- doc/website/index.md
According to the HTML specification, `alt` is specified by `img`, and there is no additional workaround in the web platform for the authors' errors in calculating the accessible name for the `picture` case.
> Typo fix. Move the alt text attribute to an element where it is allowed and works

- src/request.c
- src/session.c
The error where triggered with `G_MESSAGES_DEBUG=all` when starting `xdg-desktop-portal` and then starting Busttle (DBus tool). It also happen along while running in regular use.
> gtask: make sure to call g_task_return_*()

- data/org.freedesktop.impl.portal.FileChooser.xml
- data/org.freedesktop.portal.FileChooser.xml
- src/file-chooser.c
xdg-desktop-portal does not do the normalization, this is up to backends, and it's now documented that they have to do this. But we can validate the received URIs. Do that.
> Ensure FileChooser dialog only sends file:// URIs to apps

- tests/.pytest.ini
- tests/meson.build
Trying to figure out the environment variables to set to run the tests
manually is annoying, so let's use technology to solve that and pretend
we're living in the future where technology actually helps us.
And this glorious future now allows us to do:
```
$ meson devenv -Cbuilddir
$ pytest
$ ./tests/test-portals
```
and so on.
> tests: Add a devenv for our most common test environment

- data/org.freedesktop.impl.portal.GlobalShortcuts.xml
- data/org.freedesktop.impl.portal.RemoteDesktop.xml
- data/org.freedesktop.impl.portal.ScreenCast.xml
impl.portals don't use that, they just return the results direct.
> doc: Correct a few impl.portals refering to the Request.Response signal

- document-portal/document-portal-fuse.c
- document-portal/document-portal.c
- document-portal/permission-db.c
- src/xdp-utils.c
- tests/account.c
- tests/limited-portals.c
- tests/test-doc-portal.c
- tests/test-document-fuse.py
- tests/test-document-fuse.sh
- tests/test-permission-store.c
- tests/test-portals.c
This fixes https://github.com/flatpak/xdg-desktop-portal/issues/689
The mechanism we're using to flush the dcache and thus avoiding long-term caching of physical inodes which keep a file descriptor open doesn't seem to work quite right.
A trivial test of cat /run/user/1000/doc/$docid/$filename properly leads to the PhysicalFile being freed. However, an application that keeps the file open for a longer time (longer than the delay we have before the current dcache flush workaround is run), ends up with the dcache entry for the inode to be kept in cache. This means that we when the last other kernel reference (like an open fd) to the inode is gone we don't get a FORGET event from fuse, and thus we never free the PhysicalInode.
This is clearly visible, because if you end up with the file …
> Fix lead of file descriptors for PhysicalInode:s

- meson.build
In this case flatpak_dep is never set and meson fails while generating the summery. And the interfaces are build based on the content of flatpak_intf_dir anyways, so use that in the summary.
> meson.build: fix building when flatpak-interfaces-dir is explicitly specified

- src/portal-impl.c
x-d-p-gtk has historically been used as the portal implementation of last resort, and in particular, users of assemble-it-yourself desktop environments or otherwise-unsupported desktop environments have tended to rely on it for basic functionality, particularly now that its GNOME-specific parts have been removed.
We don't want to install a /usr/share/x-d-p/portals.conf that makes it the fallback (as proposed in xdg-desktop-portal#1192) because that would be higher-precedence than the fallback to the legacy UseIn mechanism. For example, x-d-p-wlr has UseIn=...;Wayfire;... which means that it will be used to provide screenshots and screencasts under Wayfire (even without fixing WayfireWM/wayfire#1995), but installing a /usr/share/x-d-p/portals.conf with only default=gtk would defeat that. …
> portal-impl: Hard-code x-d-p-gtk as a last-resort fallback

- src/background.c
- src/location.c
- src/open-uri.c
- src/wallpaper.c
- src/xdp-utils.c
- src/xdp-utils.h
There are a number of cases where there is an assumption that the portal ID + ".desktop" will match the desktop file for an application.
In the case of snaps, this cases a NULL app info with the following error:
```
(/usr/libexec/xdg-desktop-portal:1958136): GLib-GIO-CRITICAL **: 10:27:05.777: g_app_info_get_display_name: assertion 'G_IS_APP_INFO (appinfo)' failed
(/usr/libexec/xdg-desktop-portal:1958136): GLib-GIO-CRITICAL **: 10:27:05.777: g_desktop_app_info_has_key: assertion 'G_IS_DESKTOP_APP_INFO (info)' failed
```
And the access dialog in the shell fails due to it making the same assumption:
```
** (/usr/libexec/xdg-desktop-portal:1958136): WARNING **: 10:27:05.779: Failed to show access dialog: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Only the focused app is allowed to …
```
> Fix cases where the portal id is assumed to match the .desktop file name

- data/org.freedesktop.impl.portal.Access.xml
- data/org.freedesktop.impl.portal.Clipboard.xml
- data/org.freedesktop.impl.portal.DynamicLauncher.xml
- data/org.freedesktop.impl.portal.FileChooser.xml
- data/org.freedesktop.impl.portal.GlobalShortcuts.xml
- data/org.freedesktop.impl.portal.Inhibit.xml
- data/org.freedesktop.impl.portal.InputCapture.xml
- data/org.freedesktop.impl.portal.Notification.xml
- data/org.freedesktop.impl.portal.Print.xml
- data/org.freedesktop.impl.portal.RemoteDesktop.xml
- data/org.freedesktop.impl.portal.ScreenCast.xml
- data/org.freedesktop.portal.Account.xml
- data/org.freedesktop.portal.Background.xml
- data/org.freedesktop.portal.Camera.xml
- data/org.freedesktop.portal.Clipboard.xml
- data/org.freedesktop.portal.DynamicLauncher.xml
- data/org.freedesktop.portal.FileChooser.xml
- data/org.freedesktop.portal.GlobalShortcuts.xml
- data/org.freedesktop.portal.Inhibit.xml
- data/org.freedesktop.portal.InputCapture.xml
- data/org.freedesktop.portal.Location.xml
- data/org.freedesktop.portal.Print.xml
- data/org.freedesktop.portal.RemoteDesktop.xml
- data/org.freedesktop.portal.ScreenCast.xml
- data/org.freedesktop.portal.Screenshot.xml
- data/org.freedesktop.portal.Secret.xml
Unfortunately relies on https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3751 to have fixed anchors generation to fix them all.
Fix all broken rST refs  (red links) in the documentation.
> doc: Fix broken rST refs

- data/org.freedesktop.portal.OpenURI.xml
This clarifies in more detail why you would use this over OpenFile() and how it operates in general.
> docs: Add more detail to the OpenDirectory() method

- src/account.c
- src/background.c
- src/device.c
- src/dynamic-launcher.c
- src/email.c
- src/file-chooser.c
- src/global-shortcuts.c
- src/inhibit.c
- src/input-capture.c
- src/location.c
- src/open-uri.c
- src/print.c
- src/remote-desktop.c
- src/screen-cast.c
- src/screenshot.c
- src/secret.c
- src/wallpaper.c
The org.freedesktop.impl.portal.Request interface has no properties, and is constructed against a different object path. We don't need to fetch properties for that.
Don't do that.
Closes: https://github.com/flatpak/xdg-desktop-portal/issues/1241
> impl-request: Do not load properties on construction

- src/device.c
See https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/35.
I did my best but I was not able to test this in action.
> device: Improve dialog text

- tests/test-document-fuse.sh
The syntax to output to stderr was incorrect
> test: The test were leaving '2' files behind

- document-portal/document-portal-fuse.c
> document-portal: Minor indentation and typo fixes

- data/org.freedesktop.impl.portal.Settings.xml
- data/org.freedesktop.portal.Settings.xml
High Contrast is a feature where, much as the name implies, the contrast of applications that support the feature is increased, whether it be adding more opacity to lines in applications, or in the rare case changing the entire palette of an application to be of the maximum possible colour contrast. Irregardless of implementation, this hint has existed for quite a long time in the UNIX space, as well as existing in most other Operating Systems, and this pull request gives this long-standing accessibility hint a standardised location for both existing and future uses of high contrast to come.
A new key on the settings portal, `high-contrast`, would be introduced into the `org.freedesktop.appearance` namescape. This key will use a boolean value.
The design of this key is based on every …
> High Contrast hint on settings portal

- doc/portals.conf.rst.in
The ScreenCast interface name was misspelled and the typo has been already copied to various projects.
> doc: fix typo in the portals.conf example

- tests/camera.c
- tests/inhibit.c
- tests/limited-portals.c
- tests/test-portals.c
- tests/test_globalshortcuts.py
- tests/test_remotedesktop.py
- tests/wallpaper.c
Because programs running in a non gnome-terminal belong to a .scope unit starting with app, xdg-desktop-portal assings a non empty appid to them. On the other hand, for setting permissions into the permission store, tests assume that appid is the empty string. To fix this, retrieve the appid during global setup a,d store it in a global variable. It is then available to tests, and can be passed when setting permissions.
Fix 3 test failures out of 5 reported in #1278
The other failures are in python tests.
> Fix test failures on non gnome-terminal in GNOME

- data/org.freedesktop.portal.FileChooser.xml
The application should not depend on where the URL points, or how access to the file is granted, just that access has been granted at that URL.
@matthiasclasen, I've set you as the commit author since I used the wording you suggested on Matrix.
> docs: clarify guarantees of the File Chooser API

- data/org.freedesktop.portal.FileChooser.xml
This appears to have been incorrectly copied and pasted from the request options vardict.
> docs: remove nonexistent FileChooser SaveFile result

- src/portal-impl.c
Don't use fallback portal implementations in the following cases:
- the preferred portals for an interface contains `none`
- no preference is set for the interface but the default preference contains `none`
Fixes https://github.com/flatpak/xdg-desktop-portal/issues/1254
> fix: fallback implementation is used if preferred value of none

- data/org.freedesktop.portal.Screenshot.xml
Same as c7dce4e ("docs: clarify guarantees of the File Chooser API").
(I've checked, and no other portal documentation mentions /run/user apart from the document portal, so this should be the last of these fixes.)
> docs: clarify guarantees of the Screenshot API

- src/pipewire.c
- src/pipewire.h
This practically reintroduces commit fbe26534e14 which got reverted in ff8a8de6aedb5, which I only discovered after coming up with this solution on its own. The only difference is that
`discover_node_factory_sync()` gets removed as it doesn't really make much sense to keep around.
The commit message of fbe26534e14 (by msizanoen1
<qtmlabs@protonmail.com>)>
```
Currently, the PipeWire registry object is destroyed when
discover_node_factory_sync finishes its functionality. This causes
registry events to not be delivered to the global_removed_cb and
global_added_cb callbacks after discover_node_factory_sync, breaking
the functionality of the
org.freedesktop.portal.Camera.IsCameraPresent property in case of
camera device hot(un)plug.
This changes the discover_node_factory_sync function to …
```
> pipewire: Destroy registry object with remote

- src/open-uri.c
When OpenURI was called with a file-descriptor to a file whose path was not available (whether due to sandboxing or race conditions) this caused an obscure crash, which is resolved by this commit.
This fixes https://retrace.fedoraproject.org/faf/problems/603686/
> Fix segfault when opening non-existant file

- data/org.freedesktop.impl.portal.Print.xml
- data/org.freedesktop.portal.Print.xml
- src/camera.c
- src/xdg-desktop-portal.c
- tests/testdb.c
Addresses some (apparently harmless) compiler warnings, and shuffles some stuff around.
No functional changes.
> Unassorted cleanups

- src/launch-context.c
GAppLaunchContext.get_startup_notify_id() expects a string copy, not a const string. Call g_strdup() to copy the string.
> launch-context: Return a copy of the token string

- src/camera.c
The permission should be set to NO or YES only if the choice came from the user.
Fixes: https://github.com/flatpak/xdg-desktop-portal/issues/1338
> camera: Do not set permission=no on errors

- src/device.c
The permission should be set to NO or YES only if the choice came from the user.
Fixes: https://github.com/flatpak/xdg-desktop-portal/issues/1338
(cherry picked from commit 8049324038cd9fd63bf6c13aca004f85f4bf0255)
> device: Do not set permission=no on errors

- src/portal-impl.c
The default_portal pointer can be NULL if there is no default portal set in the configuration. In that case the default portal is not explicitly set to "none" and we return FALSE in portal_default_prefers_none.
Fixes: 1394bb2 ("portal-impl: fallback implementation is used if preferred value is none")
Closes: https://github.com/flatpak/xdg-desktop-portal/issues/1330
> portal-impl: Check for default_portal before derefing it

- src/background.c
Check that the first commandline item doesn't start with whitespaces or
a hyphen.
Also sneakily plug a memory leak, g_variant_get_strv() is transfer-
container. Switch to g_autofree on the variable.
Mitigates: CVE-2024-32462
> background: Improve validation of commandline option

- document-portal/permission-db.c
```
May 02 22:08:23 linux xdg-permission-store[63750]: free(): double free detected in tcache 2
May 02 22:08:23 linux systemd[3051]: xdg-permission-store.service: Main process exited, code=dumped, status=6/ABRT
May 02 22:08:23 linux systemd[3051]: xdg-permission-store.service: Failed with result 'core-dump'.
```
```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007fa6f83da1cf in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007fa6f838c472 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fa6f83764b2 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007fa6f83771ed in __libc_message (fmt=fmt@entry=0x7fa6f84e978c …
```
> permissions-db: Fix GError double free

- document-portal/document-portal-fuse.c
- document-portal/file-transfer.c
This allows running the xdg-document-portal binary on 32 bit architectures.
> document-portal: Use portable formatting specifiers in debug strings

- data/org.freedesktop.portal.Documents.xml
- document-portal/document-portal.c
- tests/test-doc-portal.c
This method allows apps to get path as exists on the host filesystem for documents exported through the document portal.
This method takes a list of document IDs as a string array and returns a dictionary mapping document IDs to the paths in the host filesystem. It is expected an app making this request to have access to given list of documents.
Based on initial work made by @JakobDev
Fixes #475
> document-portal: Implement GetHostPaths

- document-portal/document-portal.c
Do not automatically free a path we get from document_entry_get_path().
From ASAN:
```
==541366==ERROR: AddressSanitizer: SEGV on unknown address 0x7f24a6f99170 (pc 0x7f24a7ea31c5 bp 0x7f24a6f99170 sp 0x7ffd9c12d570 T0)
==541366==The signal is caused by a WRITE memory access.
#0 0x7f24a7ea31c5 in __asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) (/lib64/libasan.so.8+0x441c5) (BuildId: 388cbb99455c2e2eaec79bd8db6d9a78eb39f80d)
#1 0x7f24a7f5452e in free.part.0 (/lib64/libasan.so.8+0xf552e) (BuildId: 388cbb99455c2e2eaec79bd8db6d9a78eb39f80d)
#2 0x7f24a7d6f294 in g_free (/lib64/libglib-2.0.so.0+0x5d294) (BuildId: 795136df3faa85587229ddc59d709f81d6f697df)
#3 0x4225ed in g_autoptr_cleanup_generic_gfree …
```
> document-portal: fix crash on auto-cleanup of path we don't own

- data/org.freedesktop.portal.Documents.xml
- document-portal/document-portal-fuse.c
Complementing https://github.com/flatpak/xdg-desktop-portal/pull/1364, this provides the host path as an xattr via the document portal fuse fs.
> document/fuse: Provide the document host path as xattr

- data/org.freedesktop.impl.portal.GlobalShortcuts.xml
There is no Response signal in org.freedesktop.impl.portal.Request interface. This is a copy-paste mistake from the frontend docs, where such a signal does exist.
> globalshortcuts: Fix copy-paste errors in the docs

- doc/contributing.rst
This is not hard to find with some searching, but the relevant errors are often in `dbus-monitor` output, so add a quick note.
> docs: note and describe how to develop in toolbox

- README.md
This is just a tiny thing but it was one more hurdle - `CONTRIBUTING.md` doesn't contain anything except a link to the "real" docs, so there's not much point for the README to point there.
> Make contribution link in README.md direct instead of requiring more clicks

- .github/workflows/check.yml
- src/meson.build
- src/notification.c
- src/validate-icon.c
- src/xdp-utils.c
- tests/backend/notification.c
- tests/meson.build
- tests/notification.c
- tests/notification.h
- tests/test-portals.c
Uncontroversial commits with mostly testing improvements
> Some cherry-picks from Notifications v2 (!1298)

- tests/notification.c
The commit [1] introduced an issue that the test would terminate before
it actually run, which was probably done because the expected
notification string was set to the serialized icon instead of the
actual expected notification string.
[1] https://github.com/flatpak/xdg-desktop-portal/commit/412b3ea4bb4e1425352cc1c836030d086a037dd1
> tests: Fix mistake in notification tests

- .github/workflows/check.yml
Install libportal from git, potentially checking out a similarly named branch from the author's fork.
> ci: Install libportal from git

- README.md
Inspired by https://github.com/flatpak/xdg-desktop-portal-gtk/issues/440 and various other issue reports that can be summarized as "I use (some minimal window manager or compositor), and it didn't propagate an environment variable to the activation environment".
> README: Describe the activation environment requirements for x-d-p

- document-portal/document-portal.c
- src/dynamic-launcher.c
- src/meson.build
- src/notification.c
- src/validate-icon.c
- src/xdp-app-info.c
- src/xdp-sealed-fd.c
- src/xdp-sealed-fd.h
- src/xdp-utils.c
- src/xdp-utils.h
I split out the first few commits from https://github.com/flatpak/xdg-desktop-portal/pull/1298/ that rework how the validator works and that introduce the `XdpSealdFd`.
CC: @hfiguiere and @GeorgesStavracas
> Use sealded memfd for icon validator

- src/dynamic-launcher.c
- src/notification.c
- src/validate-icon.c
- src/xdp-sealed-fd.c
- src/xdp-sealed-fd.h
- src/xdp-utils.c
- src/xdp-utils.h
See commits. The most important change is that the icon validator now requires a `--ruleset` argument
> Some follow-ups to the icon validator

- src/portal-impl.c
This PR aims to supersede #1240. 
Original PR message:
> Quoting portals.conf(5):
> 
>     Each key in the group contains a semi-colon separated list of portal backend
>     implementation, to be searched for an implementation of the requested interface,
>     in the same order as specified in the configuration file.
> 
> But this wasn't actually true. If the portals were set to z;y and z and y both implemented the same portal, y would be used.
> 
> Fixing this requires reworking how portals are selected — going through the config file and selecting the first available configured portal, rather than going through each known portal and checking whether it's allowed in the config file.
> 
> find_all_portal_implementations() is unchanged. The portal-first approach is fine for it, and it …
> portal-impl: fix config ordering (supersedes #1240)

- document-portal/permission-db.c
- src/open-uri.c
- src/xdp-app-info-flatpak.c
- src/xdp-app-info.c
- src/xdp-utils.c
- tests/test-doc-portal.c
- tests/test-permission-store.c
3 independent patches.
Use g_steal_pointer to make sure there is no double free
I hit this testing my USB portal changes:
```
=================================================================
==2042089==ERROR: AddressSanitizer: heap-use-after-free on address 0x502000109898 at pc 0x0000005ba818 bp 0x7fbc501ff420 sp 0x7fbc501ff418
READ of size 8 at 0x502000109898 thread T14
#0 0x5ba817 in authorize_callback ../src/xdg-desktop-portal.c:141
#1 0x7fbc672a7dcf in _g_cclosure_marshal_BOOLEAN__OBJECT.part.0 (/lib64/libgio-2.0.so.0+0x76dcf) (BuildId: 1a20350aab8ff50007bb0131898dc24973f8b164)
#2 0x7fbc671e3649 in g_closure_invoke (/lib64/libgobject-2.0.so.0+0x11649) (BuildId: 327e1dbd4b402ab1171d32553c27b5a07e36af7d)
#3 0x7fbc672135f2 in signal_emit_unlocked_R.isra.0 …
```
> Regression fixes

- doc/for-desktop-developers.rst
Fix the ref link which is linked to this warning while generating docs:
```
../doc/for-desktop-developers.rst:102: WARNING: unknown document: '/doc-org.freedesktop.background.Monitor.rst' [ref.doc]
```
> doc: Fix Background Monitor Apps ref link

- src/background.c
- src/camera.c
- src/clipboard.c
- src/global-shortcuts.c
- src/inhibit.c
- src/input-capture.c
- src/location.c
- src/open-uri.c
- src/remote-desktop.c
- src/remote-desktop.h
- src/request.c
- src/request.h
- src/screen-cast.c
- src/screenshot.c
- src/session.c
- src/session.h
- src/wallpaper.c
We would usually get them from the G_DECLARE_TYPE macro family but we cannot use them right now because they have no namespace and the derivable classes would need private data and our data is public.
For now, just define the functions manually where it makes sense. In the longer term, we should switch towards the G_DECLARE_TYPE macros.
> Add cast and type-check functions for Session and Request

- src/dynamic-launcher.c
- src/xdp-app-info-flatpak.c
- src/xdp-app-info-host.c
- src/xdp-app-info-private.h
- src/xdp-app-info.c
- src/xdp-app-info.h
This is a continuation of https://github.com/flatpak/xdg-desktop-portal/pull/1369.
> XdpAppInfo refactoring, Part 3

- tests/share/applications/meson.build
These are required to be in `XDG_DATA_DIR` when the installed tests are run
> tests: install files required for `installed_tests`

- data/org.freedesktop.impl.portal.ScreenCast.xml
- data/org.freedesktop.portal.ScreenCast.xml
The name "virtual" is too ambiguous by itself so a blurb is added for each type.
> doc: Add ScreenCast source type meaning

- .github/workflows/build-and-test.yml
- .github/workflows/check-potfiles.sh
- .github/workflows/release.yml
- RELEASE_HOWTO.md
Depends on https://github.com/flatpak/xdg-desktop-portal/pull/1334
> ci: Automate releases and check POTFILES.in

- data/org.freedesktop.portal.GlobalShortcuts.xml
- data/org.freedesktop.portal.Inhibit.xml
- data/org.freedesktop.portal.RemoteDesktop.xml
- data/org.freedesktop.portal.ScreenCast.xml
This was erroneously implemented as `s` but for backwards compatibility cannot be changed as it would break existing clients. Best we can do here is fix the documentation and tell people about it.
See eebb04172d00 ("use correct type for the session object path") and its revert in e4523531c.
Closes #1359
> data: Document the session_handle type mismatch

- doc/pull-requests.rst
This should hopefully take people to the right place if they bother to read the documentation.
Closes: https://github.com/flatpak/xdg-desktop-portal/issues/1441
> doc: Link to github discussions, issues and pull request pages

- src/portal-impl.c
- src/portal-impl.h
The last commit is the real deal.
Closes https://github.com/flatpak/xdg-desktop-portal/issues/1455
> Portal config cleanups and a fix

- data/org.freedesktop.portal.Settings.xml
Explicitly calls the keys which we document "standardized keys" and moves the text about non-standardized keys closer to that and before the list of keys so it's harder to miss.
> settings: Make the text about non-standardized keys prominent

- data/org.freedesktop.portal.GlobalShortcuts.xml
The method result's shortcuts list is the list of shortcuts which were actually bound. It's valid to send any subset of shortcuts that were passed in by the caller.
See: https://github.com/flatpak/xdg-desktop-portal/issues/1350
@dcz-self @davidedmundson
> globalshortcuts: Specify the shortcuts result of BindShortcuts

- data/org.freedesktop.portal.OpenURI.xml
- src/open-uri.c
- tests/openuri.c
- tests/openuri.h
- tests/test-portals.c
To check whenever specific scheme is supported by the host.
> Add SchemeSupported to the OpenURI portal

- .github/workflows/container.yml
This allows PRs to get through CI when they have changes in the required image.
> ci: Use images from actor instead of owner

- .github/workflows/container.yml
Only fall back to the actor's image if the repository owner ones does not exist.
> ci: Prefer repository owner image if it exists

- src/notification.c
Main commit:
```
notification: Use separate fd list for input and output
Doing this means we don't unnecessarily forward file descriptors that
weren't intended to be passed along.
For the notification portal, this avoids forwarding file descriptors
from the app to the backend that were dropped due to being placed in an
unsupported property.
```
I haven't tested this yet, I just ran the tests.
> Avoid forwarding all notification file desciptors to backend

- .github/workflows/Containerfile
- .github/workflows/container.yml
- .github/workflows/pages.yml
Fixes the current messed up CSS/theme in https://flatpak.github.io/xdg-desktop-portal/docs/index.html, deployed at https://bbhtt.github.io/xdg-desktop-portal/docs/index.html
> ci: Install doc dependencies via pip

- src/portal-impl.c
Since 1.18.2, we have a hardcoded fallback to xdg-desktop-portal-gtk as a last resort if no other portal is defined by a configuration file. This fallback mechanism, however, isn't implemented for the org.freedesktop.impl.portal.Settings interface.
The consequence is that everything seems to work just fine, but user preferences like color scheme are ignored in applications that use the portal API to retrieve them (not just flatpak apps, also libadwaita apps). That comes as a surprise to users; and since the portal stuff otherwise works fine, it's not entirely straightforward to figure out that configuring portal.conf would fix it.
I believe that if [`find_portal_implementation`](https://github.com/flatpak/xdg-desktop-portal/blob/ef1e96b51be6313f524279cd77c8261d1e5186ba/src/portal-impl.c#L5 …
> portal-impl: Use fallback portals for Settings as well

- data/org.freedesktop.portal.Notification.xml
- tests/notification.c
See the individual commits for changes.
> Follow up notification v2

- src/account.c
- src/background.c
- src/camera.c
- src/clipboard.c
- src/dynamic-launcher.c
- src/email.c
- src/file-chooser.c
- src/global-shortcuts.c
- src/inhibit.c
- src/input-capture.c
- src/location.c
- src/network-monitor.c
- src/notification.c
- src/open-uri.c
- src/print.c
- src/remote-desktop.c
- src/restore-token.c
- src/screen-cast.c
- src/screenshot.c
- src/secret.c
- src/session.c
- src/wallpaper.c
* Always initialize g_auto(GVariantBuilder)
* Use g_auto and G_VARIANT_BUILDER_INIT for all GVariantBuilders
One has to be very careful about the control flow and early exits
without the g_auto which can easily result in memory leaks. I noticed at
least 5 cases where the change does fix a leak, even though it might be
a bit hard to trigger.
This also makes sure that all g_auto usages are initialized correctly.
> Use g_auto and G_VARIANT_BUILDER_INIT for all GVariantBuilders

- data/org.freedesktop.portal.Notification.xml
- src/notification.c
- tests/notification.c
The xdg spec¹ uses slightly different names thus making it hard for apps
to use API like `g_notification_set_category` in a way that works for
portaled and non-portaled use cases.
It also makes things slighlty more consistent as the current call.*
sub-categories (`.incoming`, `.ongoing`) indicate a state while the `im`
category indicates a type (`message`).
1) https://specifications.freedesktop.org/notification-spec/1.2/categories.html
> notification: Use categories from xdg desktop notification spec

- src/xdp-utils.c
- tests/README.md
Resolves #1497.
In limited build environments, the tests can be run as:
```
XDP_VALIDATE_ICON_INSECURE=1 XDP_VALIDATE_SOUND_INSECURE=1 meson test -C ${builddir}
```
(variable names chosen to discourage users from making use of this in production to validate genuinely untrusted icons/sounds).
* xdp_validate_icon: Assign argument indices automatically
* xdp_validate_icon: Allow sandboxing of the validator to be disabled
OS distributions often compile packages and run their build-time tests
in a chroot environment or an unprivileged container, and bubblewrap
cannot usually work in either of those environments.
* xdp_validate_sound: Assign argument indices automatically
* xdp_validate_sound: Allow sandboxing of the validator to be disabled
Same reasoning as for the icon validator.
> Allow build-time tests to be run in environments where bwrap can't work

- src/camera.c
- tests/camera.c
Sending an app id that doesn't resolve to valid app info (e.g. a desktop file is not found) will automatically reject camera request, because the backend is not able to verify whether the app (based on app id) runs in the background. Same will happen if the app id resolves to an app where our app was started from. This happens for example when you start apps
in GNOME using Alt + F2, where we get invalid app id from cgroups and since it doesn't find opened application window for this app, it will automatically reject the request. Using an empty id fixes this problem.
> Camera: use an empty app id for host apps

- src/camera.c
Backport of https://github.com/flatpak/xdg-desktop-portal/pull/1512.
> [1.18] Camera: use an empty app id for host apps

- meson.build
Without this the build fail if you have libportal 0.8.1 installed
This is needed for the notification work.
> test: Depend on a recent enough version of libportal

- src/settings.c
- src/xdg-desktop-portal.c
- src/xdp-portal-impl.c
- tests/__init__.py
- tests/conftest.py
- tests/meson.build
- tests/templates/__init__.py
- tests/templates/settings.py
- tests/test_settings.py
Based on https://github.com/flatpak/xdg-desktop-portal/pull/1536
> Use all requested setting backends again [cont]

- .github/workflows/release.yml
So we can run the release action and skip the USB test, which is known to be failing only on CI.
> ci: Set XDP_TEST_IN_CI in the release workflow too

- tests/meson.build
- tests/template.test.in
* tests: Set XDG_DATA_DIRS for as-installed testing
test-portals-openuri.test will fail if it can't find furrfix.desktop
(a mockup of Firefox) in the search path.
We also need to make sure the build-time datadir and the default data
directories /usr/local/share and /usr/share are still in the search path,
for GSettings schemas.
> tests: Set XDG_DATA_DIRS for as-installed testing

- src/xdp-app-info-flatpak.c
- src/xdp-app-info-host.c
The dynamic launcher portal is broken in postmarketOS v24.12. Seems the `xdp_app_info_flatpak_is_valid_sub_app_id()` and `xdp_app_info_host_is_valid_sub_app_id()` were forgotten to be added to the `class_init()` functions.
> XdpAppInfo: set missing is_valid_sub_app_id in class_init

- tests/test_usb.py
We disabled the test in CI because the tests were failing but we didn't understand why in
06a5e502 ("test: Disable USB removal test in a container")
It turns out that UMockdev simply didn't send the remove event before version 0.18.4. Let's change the skip condition to actually check for the right thing instead of just disabling it in CI. This means that the test will run in CI once ubuntu:latest does have the right version.
> tests/usb: Skip the removal tests when the UMockdev version is too old

- tests/meson.build
We can only use the python object if it was found and the arguments for require are all evaluated, even if the resulting feature is disabled.
Fixes: 1c6dd182 ("tests: Check for required WAV decoder for notification tests")
Closes: https://github.com/flatpak/xdg-desktop-portal/issues/1547
> build/tests: Check for python found and version in single require call

- meson.build
- tests/meson.build
- tests/notification.c
Only sound-related tests require gstreamer wavparse plugin for validation, so it's okay to disable test_notification_sound but keep other notification tests.
This also fixes link failures when wavparse isn't available: we previously excluded notification.c from the source list in the missing case, but still used test_notification_* symbols in test-portals.c.
Fixes: 1c6dd18 ("tests: Check for required WAV decoder for notification tests")
> tests: disable only sound-related notification tests if without wavparse

- src/xdg-desktop-portal.c
If no settings portal implementations are found, the `settings_create()` function currently returns NULL and the `No skeleton to export` warning is emitted. This change guards against that, which is more consistent with the other portals.
> settings: Do not export without implementations

- src/camera.c
6cd99b04d438b1de9b25c7bd928e541609904db3 changed the logic that the camera portal uses to look up permissions for the AccessCamera method. Applications first call AccessCamera to ensure they have camera permission and to prompt the user if permission is missing, then they call OpenPipeWireRemote, which fails if permission is missing. The permission lookup logic needs to be the same in both places. Currently when running Snapshot launched by GNOME Shell (rather than launched in a terminal), Snapshot passes AccessCamera's permission check, then fails OpenPipeWireRemote's permission check, causing camera access to be denied without allowing the user to grant permission.
Also, since the same commit the code uses the XdpAppInfo on a secondary thread. I suspect this is unsafe, and the original …
> camera: fix permission check in OpenPipeWireRemote

- tests/conftest.py
Alternative to https://github.com/flatpak/xdg-desktop-portal/pull/1577 which implements it directly in the pytest conftest which should work transparently for build and installed tests.
/cc @smcv
> tests: Translate pytest exit status to Meson/ginsttest-runner convention [pytest approach]

- tests/.pytest.ini
It was originally added in 8100fc4b to prevent the meson logs getting picked up by pytest.
The pytests are now being run from the source tree instead of the build dir so it is safe to remove the filen.
> tests/py: Remove pytest.ini

- tests/conftest.py
- tests/meson.build
- tests/template-tap.test.in
- tests/template.test.in
- tests/test_document_fuse.py
I personally don't really understand the value of installed tests, so this is more of an question if it makes sense to do it.  The plan is to remove the C based tests soon which would mean we'd have no more installed tests.
Only the last commit is relevant.
/cc @smcv
> Install pytest based tests

- document-portal/document-portal-fuse.c
- tests/test_documents.py
See: https://github.com/flatpak/xdg-desktop-portal/discussions/1563
> document/fuse: Make the host-path xattr more useful

- tests/__init__.py
- tests/conftest.py
- tests/templates/__init__.py
- tests/templates/access.py
- tests/templates/account.py
- tests/templates/appchooser.py
- tests/templates/background.py
- tests/templates/clipboard.py
- tests/templates/email.py
- tests/templates/filechooser.py
- tests/templates/geoclue2.py
- tests/templates/globalshortcuts.py
- tests/templates/inhibit.py
- tests/templates/lockdown.py
- tests/templates/notification.py
- tests/templates/print.py
- tests/templates/remotedesktop.py
- tests/templates/screenshot.py
- tests/templates/settings.py
- tests/templates/usb.py
- tests/templates/wallpaper.py
Print everything to stdout/stderr. Currently the logging of all the templates never made it to the output of pytest, and the logging in `tests/__init__.py` ends up in a completely different section (the python log capture, instead of the stdout/stderr capture) which makes it hard to tell the order of things.
> Tests logging

- tests/meson.build
Instead of filtering with -k. This is more precise and allows adding additional filters with -k more easily.
> build: Change the pytest invocation to run a specific file

- data/meson.build
- data/org.freedesktop.host.portal.Registry.xml
- document-portal/document-portal.c
- document-portal/file-transfer.c
- src/camera.c
- src/location.c
- src/meson.build
- src/registry.c
- src/registry.h
- src/xdg-desktop-portal.c
- src/xdp-app-info-flatpak-private.h
- src/xdp-app-info-flatpak.c
- src/xdp-app-info-host-private.h
- src/xdp-app-info-host.c
- src/xdp-app-info-snap-private.h
- src/xdp-app-info-snap.c
- src/xdp-app-info.c
- src/xdp-app-info.h
- tests/__init__.py
- tests/meson.build
- tests/templates/__init__.py
- tests/templates/globalshortcuts.py
- tests/templates/inhibit.py
- tests/templates/remotedesktop.py
- tests/test_registry.py
For host apps, we currently require applications to run inside a cgroup with a name that allows xdg-desktop-portal to derive an application ID from it. This does not work reliably, and while the situation can improve, it's unlikely to ever be fool proof, as it in theory requires every potential piece of software that launches other applications to know how to launch it in a compatible way.
Cgroups is also a Linux specific API, which is problematic from a *nix wide portability perspective.
To address this, introduce a host-only portal API that allows applications to register their D-Bus connections, associating them with an application ID. This moves back the burden of associating an application with an application ID back to the application itself, instead of the application launcher. …
> Allow host apps to register themselves

- src/xdp-session.c
- tests/test_remotedesktop.py
The token is used as part of an object path so it has to meet those requirements. We can't escape it since the caller presumably expects to use the token as-is so where it fails the validity simply error out.
Closes: https://github.com/flatpak/xdg-desktop-portal/issues/1549
> session: Validate the token for correctness

- tests/__init__.py
- tests/templates/__init__.py
- tests/templates/access.py
- tests/templates/account.py
- tests/templates/appchooser.py
- tests/templates/dynamiclauncher.py
- tests/templates/email.py
- tests/templates/filechooser.py
- tests/templates/globalshortcuts.py
- tests/templates/inhibit.py
- tests/templates/print.py
- tests/templates/remotedesktop.py
- tests/templates/screenshot.py
- tests/templates/usb.py
- tests/templates/wallpaper.py
The portal backend mocks would all implement the same pattern by copy
and pasting a bunch of code which is not that easy to understand and
also subtly broken because they would often not unexport the request
object.
This changes the ImplRequest to own the control flow and do all the
right things in a single place and provides callbacks for more advanced
use cases.
> tests/templates: Rework ImplRequest

- src/input-capture.c
- tests/templates/inputcapture.py
- tests/test_inputcapture.py
For a reason that i ignore, this signal was never passed from the xdg-desktop-portal impl to the application
> input-capture: hookup ZonesChanged signal

- src/pipewire.c
While submitting pipewire 1.3.82 to openSUSE Tumbleweed I noticed this cast is needed to build xdg-desktop-portal. This was already submitted as an issue in #1611 in Debian testing, in which the reporter doesn't mention the used pipewire version but says "I am also building my own pipewire" so I guess it's one of the latest RCs (1.3.81 or 1.3.82).
Fixes: #1611
> Fix build with pipewire 1.3.82

- tests/meson.build
I did an oopsie while rebasing the branch containing 005da4c3 and partially undid fedbd63c ("build: Change the pytest invocation to run a specific file").
Fixes: 005da4c3 ("build: Use a single `tests` option to control if we build any tests")
> test: Fix calling pytest from meson

- doc/api-reference.rst
- doc/fix-rst-dbus.py
- doc/meson.build
- src/meson.build
- src/xdg-desktop-portal.c
- tests/meson.build
For the 1.20 release. This should be reverted once that's released.
> Temporarily neutralize the host app registry

- tests/meson.build
- tests/run-test.sh
Running the tests outside of meson gives more control but also requires setting up a bunch of environment variables. The new script sets everything up automatically if the standard build directory is used.
> tests/run-test.sh: Add new tool to simplify running tests

- tests/run-test.sh
This resolves several warnings from shellcheck about patterns that will not do what was intended, because shell script is a language constructed entirely from sharp edges.
> run-test.sh: Quote more defensively

- src/notification.c
- tests/test_notification.py
* notification: Escape the href attribute of links when re-serializing
Otherwise they'll be emitted unescaped, changing the meaning of the
notification body.
Fixes: ebff872d "notification: Add new property markup-body to support markup"
Resolves: https://github.com/flatpak/xdg-desktop-portal/issues/1545
* tests: Assert that href attributes are escaped correctly
Strictly speaking the exact form of escaping used here is an
implementation detail of GLib (it would be equally valid to re-escape
the encoded characters with numeric character references like
`&#34;&#62;&#60;html&#62;` or similar), but it seems unlikely that
GLib will change this in practice.
* notification: Escape the body text of the markup-body when re-serializing
Similar to #1545, otherwise they'll be emitted unescaped, …
> notification: Escape the href attribute of links when re-serializing

- doc/convenience-libraries.rst
This adds https://github.com/rymdport/portal to the list of convenience libraries.
> Add the Go package to list of libraries

- document-portal/document-portal.c
- document-portal/permission-store.c
- src/xdg-desktop-portal.c
- tests/README.md
This is especially useful when the binaries are run as part of a test and getting the debugger to the right place takes a bit of effort.
Without the `raise (SIGCONT);` I get into a loop of SIGSTOPs in gdb and I don't understand why.
> Wait for debugger

- doc/api-reference.rst
- doc/fix-rst-dbus.py
- doc/meson.build
- src/meson.build
- src/xdg-desktop-portal.c
- tests/meson.build
From the last commit:
Since the plan is for apps to eventually ensure they are placed in the
right cgroup and rely on the portal to derive the app ID from the cgroup
name, mention this in the api reference.
Time will tell when we'll be able to make this transition, but at least document the "stop gap"-ness of the registry solution.
Cc: @pwithnall
> Unneutralize host registry and document the plans for the future

- data/org.freedesktop.portal.Usb.xml
These are broken at https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Usb.html.
> usb: docs: Fix links to Session and Request

- tests/run-test.sh
Solving the problem that https://github.com/flatpak/xdg-desktop-portal/pull/1638 is trying to solve but with a fallback from pytest-3 to pytest.
> tests/run-test.sh: Fall back from pytest-3 to pytest

- src/xdg-desktop-portal.c
The invocations are currently delegated to threads which means that the next invocation gets run before the first one finished. This is fine for all the other portals, but because the Registry modifies the identity of the caller for all following calls, we must ensure that it finishes before the next invocation. This means in particular no g-authorize-method and no FLAGS_HANDLE_METHOD_INVOCATIONS_IN_THREAD.
> Make sure the Host Registry XdpAppInfo updates become visible

- doc/for-contributors.rst
Add missing "between" in paragraph 1, remove extra "the" in paragraph 2.
> docs: Fix typos in for-contributors.rst

- src/meson.build
- src/xdp-app-info-flatpak.c
- src/xdp-app-info-host.c
- src/xdp-app-info-private.h
- src/xdp-app-info-snap.c
- src/xdp-app-info-test.c
- src/xdp-app-info.c
See commits. This is the first part of https://github.com/flatpak/xdg-desktop-portal/pull/1614
> XdpAppInfo cleanups

- src/realtime.c
The PID is useful when debugging issues related to these messages, so we can check whether the PID has some strange property that caused the problem.
In my case, this made it easier to debug #1653 - the PID showed it was caused by Firefox, so I knew to look there.
> realtime: Include PID/TID in some error messages

- data/org.freedesktop.impl.portal.GlobalShortcuts.xml
- data/org.freedesktop.portal.GlobalShortcuts.xml
- data/org.freedesktop.portal.RemoteDesktop.xml
- data/org.freedesktop.portal.Screenshot.xml
- doc/api-reference.rst
Makes the Global Shortcuts description actually show up in the docs and the website, fixes a few links and manages to reduce the number of warnings being generated when building the docs.
Closes: #1663
> doc: Fix a few typos and wrong references

- src/validate-icon.c
- src/validate-sound.c
otherwise running from /tmp (e.g. for tests) will fail
> validate-{icon,sound}: mount tmpfs,proc,dev first

- src/xdp-portal-impl.c
Continuation of https://github.com/flatpak/xdg-desktop-portal/pull/1561 to resolve https://github.com/flatpak/xdg-desktop-portal/issues/603.
Tried for a few hours to get proper tests for the configuration (unshare, setting xdg base dir env, ...) but gave up in the end.
> Load portal config from data dirs with priority

- src/input-capture.c
Copy/paste error from the Activated handling: A Deactivated signal changes the input capture session back into ENABLED.
> input-capture: Fix state after a Deactivated signal

- data/org.freedesktop.impl.portal.GlobalShortcuts.xml
- data/org.freedesktop.portal.GlobalShortcuts.xml
- src/global-shortcuts.c
- tests/templates/globalshortcuts.py
- tests/test_globalshortcuts.py
As mentioned on Matrix this allows an application to steer their users to the place where they can configure global shortcutcs of the application.
kde portal impl: https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/commit/a8b7532e33d98bdaf034a92c624bc63adaceec5c
client side impl in ashpd: https://github.com/Sodivad/ashpd/commit/21be0f546438b52be27a49a8c79c621753059c43
> GlobalShortcuts: Add a request to configure shortcuts

- NEWS.md
- README.md
- data/org.freedesktop.impl.portal.Account.xml
- data/org.freedesktop.impl.portal.GlobalShortcuts.xml
- data/org.freedesktop.impl.portal.InputCapture.xml
- data/org.freedesktop.portal.GlobalShortcuts.xml
- data/org.freedesktop.portal.InputCapture.xml
- data/org.freedesktop.portal.Usb.xml
- doc/for-desktop-developers.rst
- doc/usb-portal.md
Took the liberty of fixing more typos throughout the repo and removing newlines in the README.
Some typos were in NEWS, I looked if they corresponded to commit messages, but it seemed like they didn't, so I corrected those typos. If these are undesired changes, I'll remove them.
> doc: Fix typos in numerous files

- src/xdp-app-info-flatpak.c
Fixes: 2d8c2472 ("app-info: Steal pidfd when constructing a XdpAppInfo")
Closes: https://github.com/flatpak/xdg-desktop-portal/issues/1719
> app-info/flatpak: Steal bwrap pidfd because AppInfo doesn't dup anymore

- src/xdp-app-info-flatpak.c
- src/xdp-app-info-host.c
- src/xdp-app-info-snap.c
- src/xdp-app-info.c
> app-info: Clarify pid file descriptor ownership transfers

- src/xdp-app-info-flatpak.c
- src/xdp-app-info-snap.c
* app-info: Don't require a .desktop file for Flatpak apps
Several portal interfaces like Background, Location and Wallpaper
try to use a "main" .desktop file from the sandboxed app to provide
a "friendly name" and/or an icon. However, not all Flatpak apps export
a .desktop file of the same name as their app-ID, as demonstrated by
org.gnome.NautilusPreviewer. Portal interfaces like Background are
expected to fall back to displaying the app-ID if they cannot derive a
"friendly name" from the .desktop file.
Restore the 1.20.0 functionality by not requiring a GAppInfo
(.desktop file)
Resolves: https://github.com/flatpak/xdg-desktop-portal/issues/1718
* app-info: Don't require a .desktop file for Snap apps
It isn't clear to me whether Snap apps can lack a "main" .desktop file,
but before …
> app-info: Don't require a .desktop file for Flatpak and Snap apps

- src/xdp-app-info.c
- src/xdp-utils.c
- src/xdp-utils.h
The ioctl is the less brittle path to get the pid namespace from a pidfd, so let's try it first, and if the kernel doesn't support it, fall back to the previous code path.
> xdp-utils: Try PIDFD_GET_PID_NAMESPACE ioctl first to get pidns

- src/file-chooser.c
- src/open-uri.c
- src/xdp-documents.c
- src/xdp-documents.h
- tests/test_openuri.py
When the access to the directory is provided by the portal (like browser download directory) the stored files in the directory are not found by xdp_get_real_path_for_doc_path and /run/user/... path is opened instead of host path by the OpenFile or OpenDirectory portal.
> Try harder to find the host path for the documents

- src/camera.c
- tests/test_camera.py
This effectively reverts 6cd99b04 ("Camera: use an empty app id for host apps").
We now have the org.freedesktop.host.portal.Registry portal which allows apps to register their app id instead of relying on the currently somewhat broken auto-detection. The commit this is reverting was introduced to deal with the broken auto-detection in firefox. Firefox now uses the Registry in ESR 140, so it should be safe to revert the behavior here.
> camera: Revert using an empty app id for all host apps

- subprojects/conftest.py
cc @swick - not sure if running the subproject pytests was intentional
> subprojects: add a conftest.py so we don't run pytests

- data/org.freedesktop.impl.portal.Print.xml
- data/org.freedesktop.portal.Print.xml
- src/print.c
Print dialogs can have a feature that lets the user select 'current page' or 'selection' for what pages to print.
This only makes sense if there *is* a current page or page selection.
This information needs to be provided by the caller, which is what the new options are about.
An implementation for the gnome backends is here: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/merge_requests/229
And this MR makes gtk use the new options: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/8866
> print: Add two new options

- src/xdp-app-info-host-private.h
- src/xdp-app-info-host.c
- src/xdp-app-info.c
Let's steal the fd so it becomes absolutely clear what's going on there, and then get a new fd for xdp_app_info_host_new_registered.
> app-info: Adjust to xdp_app_info_new consuming the pidfd in

- src/global-shortcuts.c
All applications which do not have an app id, have the id "" (empty string). This means that all shortcuts they create will also be available to any other app without an app id.
This is not desireable, and since we have the host registry, we can require apps to ensure their app id is available to us.
> global-shortcuts: Require an app id to create a session
